/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: d1551003-fe11-4609-8b31-64d62c876848
-/

/-
This module defines the 2024 tax function for a single individual based on the provided brackets.
It includes the definition `tax_2024_single` and test theorems `tax_2024_single_10000` and `tax_2024_single_20000` to verify the calculation.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
Definition of the tax function for a single individual in 2024. The prompt only specified rates up to $47,150, so we default to 0 for income above that.
-/
noncomputable def tax_2024_single (income : ℚ) : ℚ :=
  if income < 0 then 0
  else if income ≤ 11600 then 0.10 * income
  else if income ≤ 47150 then 0.10 * 11600 + 0.12 * (income - 11600)
  else 0 -- Unspecified in the prompt, defaulting to 0

/-
Test theorem: Tax for $20,000 income should be $2,168.
-/
theorem tax_2024_single_20000 : tax_2024_single 20000 = 2168 := by
  rw [tax_2024_single]
  norm_num

/-
Test theorem: Tax for $10,000 income should be $1,000.
-/
theorem tax_2024_single_10000 : tax_2024_single 10000 = 1000 := by
  rw [tax_2024_single]
  norm_num