/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: cdf288a9-dc8d-46f6-9b52-3faf7edff77f
-/

/-
Formalization of IRC Section 108 (Income from discharge of indebtedness).

This module defines the necessary types and structures to represent a taxpayer's status and a discharge of indebtedness event. It implements the logic for calculating the amount excluded from gross income under §108(a) and the subsequent reduction of tax attributes under §108(b).

Key components:
- `Currency`: Defined as `Int` for precise arithmetic.
- `TaxYear`: Structure ensuring year ≥ 1913.
- `FilingStatus`: Enumeration of US tax filing statuses.
- `DischargeCategory`: Enumeration of discharge categories from §108(a)(1).
- `DischargeIndebtedness`: Structure capturing details of the debt discharge.
- `TaxpayerStatus`: Structure capturing the taxpayer's financial situation and tax attributes.
- `excludedAmount`: Function calculating the exclusion amount based on category and insolvency.
- `reduceAttributes`: Function applying the attribute reduction rules, including the 33 1/3% reduction for credits.

The module includes theorems verifying the correctness of the implementation against the legal text, such as the precedence of Title 11 exclusions and the limit on insolvency exclusions. Examples are provided to demonstrate usage.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
Basic definitions for IRC Section 108 formalization including Currency, TaxYear, and FilingStatus.
-/
-- Common definitions
def Currency := Int

structure TaxYear where
  year : Nat
  h_valid : year ≥ 1913
  deriving DecidableEq

inductive FilingStatus
  | Single                         -- IRC §1(c)
  | MarriedFilingJointly          -- IRC §1(a)
  | MarriedFilingSeparately       -- IRC §1(d)
  | HeadOfHousehold               -- IRC §1(b)
  | QualifyingWidower             -- IRC §2(b)
  | Estate                         -- IRC §1(e)(1)
  | Trust                          -- IRC §1(e)(2)
  deriving Repr, DecidableEq, Inhabited

/-
Structures for discharge categories, discharge events, and taxpayer status/attributes.
-/
-- IRC §108(a)(1) Categories
inductive DischargeCategory
  | Title11
  | Insolvency
  | QualifiedFarm
  | QualifiedRealPropertyBusiness
  | QualifiedPrincipalResidence
  deriving DecidableEq, Repr

-- Structure representing a discharge of indebtedness
structure DischargeIndebtedness where
  amount : Currency
  category : DischargeCategory
  year : TaxYear
  -- Specific condition for QualifiedPrincipalResidence (E)(ii)
  written_arrangement_before_2026 : Bool := false
  -- NEW FIELDS for §108(c)(2) compliance (QualifiedRealPropertyBusiness)
  outstanding_principal : Currency := 0
  property_fmv : Currency := 0
  deriving DecidableEq

-- Structure representing the taxpayer's status and attributes
structure TaxpayerStatus where
  insolvency_amount : Currency -- Amount by which taxpayer is insolvent immediately before discharge
  is_c_corporation : Bool
  filing_status : FilingStatus
  -- Tax attributes for §108(b)(2)
  nol : Currency
  general_business_credit : Currency
  minimum_tax_credit : Currency
  capital_loss_carryover : Currency
  basis_of_property : Currency
  passive_activity_loss_carryover : Currency
  foreign_tax_credit_carryover : Currency
  -- NEW FIELD for §108(c)(2)(B) limitation
  depreciable_real_property_basis : Currency := 0
  deriving DecidableEq

/-
Implementation of excludedAmount and reduceAttributes functions with necessary instances for Currency.
-/
-- Enable type class inference for Currency by deriving from Int
instance : LinearOrder Currency := inferInstanceAs (LinearOrder Int)
instance : AddGroup Currency := inferInstanceAs (AddGroup Int)
instance : CommRing Currency := inferInstanceAs (CommRing Int)
-- We also need division
instance : Div Currency := inferInstanceAs (Div Int)

structure TaxpayerElections where
  apply_insolvency_over_principal_residence : Bool := false
  deriving DecidableEq

/--
Calculates the amount excluded from gross income under IRC §108(a).
-/
def excludedAmount (d : DischargeIndebtedness) (s : TaxpayerStatus) (e : TaxpayerElections) : Currency :=
  match d.category with
  | DischargeCategory.Title11 => d.amount
  | DischargeCategory.Insolvency =>
    min d.amount s.insolvency_amount
  | DischargeCategory.QualifiedFarm =>
    d.amount
  | DischargeCategory.QualifiedRealPropertyBusiness =>
    -- IRC §108(a)(1)(D): "in the case of a taxpayer OTHER THAN A C CORPORATION"
    -- C corporations are INELIGIBLE for this exclusion
    if s.is_c_corporation then
      0  -- C corporations get ZERO exclusion under §108(a)(1)(D)
    else
      -- IRC §108(c)(2): Apply TWO limitations for non-C corporations
      -- Limit A: Excess of outstanding principal over FMV of property
      let limitA := max 0 (d.outstanding_principal - d.property_fmv)
      -- Limit B: Aggregate adjusted bases of depreciable real property
      let limitB := s.depreciable_real_property_basis
      -- Exclusion = min(discharge amount, min(limitA, limitB))
      min d.amount (min limitA limitB)
  | DischargeCategory.QualifiedPrincipalResidence =>
    let is_valid_date := d.year.year < 2026 || d.written_arrangement_before_2026
    if is_valid_date then
      if e.apply_insolvency_over_principal_residence then
        min d.amount s.insolvency_amount
      else
        d.amount
    else
      min d.amount s.insolvency_amount

/--
Reduces tax attributes according to IRC §108(b).
Returns the updated TaxpayerStatus.
-/
def reduceAttributes (excluded : Currency) (s : TaxpayerStatus) : TaxpayerStatus :=
  let rem := excluded
  -- (A) NOL: $1 for $1
  let nol_red := min s.nol rem
  let rem := rem - nol_red
  let s := { s with nol := s.nol - nol_red }

  -- (B) General business credit: 33 1/3 cents for $1
  -- reduction = min(credit, rem / 3)
  -- used = reduction * 3
  let gbc_red := min s.general_business_credit (rem / 3)
  let used_gbc := gbc_red * 3
  let rem := rem - used_gbc
  let s := { s with general_business_credit := s.general_business_credit - gbc_red }

  -- (C) Minimum tax credit: 33 1/3 cents for $1
  let mtc_red := min s.minimum_tax_credit (rem / 3)
  let used_mtc := mtc_red * 3
  let rem := rem - used_mtc
  let s := { s with minimum_tax_credit := s.minimum_tax_credit - mtc_red }

  -- (D) Capital loss carryovers: $1 for $1
  let cl_red := min s.capital_loss_carryover rem
  let rem := rem - cl_red
  let s := { s with capital_loss_carryover := s.capital_loss_carryover - cl_red }

  -- (E) Basis reduction: $1 for $1
  let basis_red := min s.basis_of_property rem
  let rem := rem - basis_red
  let s := { s with basis_of_property := s.basis_of_property - basis_red }

  -- (F) Passive activity loss carryovers: $1 for $1
  let pal_red := min s.passive_activity_loss_carryover rem
  let rem := rem - pal_red
  let s := { s with passive_activity_loss_carryover := s.passive_activity_loss_carryover - pal_red }

  -- (G) Foreign tax credit carryovers: 33 1/3 cents for $1
  let ftc_red := min s.foreign_tax_credit_carryover (rem / 3)
  -- let used_ftc := ftc_red * 3
  let s := { s with foreign_tax_credit_carryover := s.foreign_tax_credit_carryover - ftc_red }

  s

/-
Theorem stating that in a Title 11 case, the entire discharge amount is excluded.
-/
/--
Theorem: In a Title 11 case, the entire discharge amount is excluded.
IRC §108(a)(1)(A)
-/
theorem title11_exclusion_full (d : DischargeIndebtedness) (s : TaxpayerStatus) (e : TaxpayerElections) :
  d.category = DischargeCategory.Title11 →
  excludedAmount d s e = d.amount := by
  intro h
  simp [excludedAmount, h]

/-
Theorem stating that the insolvency exclusion is limited to the amount of insolvency.
-/
/--
Theorem: The insolvency exclusion is limited to the amount of insolvency.
IRC §108(a)(3)
-/
theorem insolvency_exclusion_limit (d : DischargeIndebtedness) (s : TaxpayerStatus) (e : TaxpayerElections) :
  d.category = DischargeCategory.Insolvency →
  excludedAmount d s e ≤ s.insolvency_amount := by
    unfold excludedAmount; aesop;

/-
Theorems verifying the precedence of Title 11 exclusion and the correctness of NOL and General Business Credit reductions.
-/
/--
Theorem: Title 11 exclusion takes precedence over other exclusions (effectively).
Since Title 11 excludes the full amount, it subsumes any partial exclusion.
-/
theorem title11_precedence (d : DischargeIndebtedness) (s : TaxpayerStatus) (e : TaxpayerElections) :
  d.category = DischargeCategory.Title11 →
  excludedAmount d s e = d.amount :=
  title11_exclusion_full d s e

/--
Theorem: Attribute reduction reduces NOL by the excluded amount, capped by the NOL available.
-/
theorem nol_reduction_correct (excluded : Currency) (s : TaxpayerStatus) :
  (reduceAttributes excluded s).nol = s.nol - min s.nol excluded := by
  unfold reduceAttributes
  simp

/--
Theorem: General Business Credit is reduced after NOL, at a rate of 33 1/3 cents per dollar.
-/
theorem gbc_reduction_correct (excluded : Currency) (s : TaxpayerStatus) :
  let rem_after_nol := excluded - min s.nol excluded
  (reduceAttributes excluded s).general_business_credit = s.general_business_credit - min s.general_business_credit (rem_after_nol / 3) := by
  unfold reduceAttributes
  simp

/-
Examples demonstrating the usage of the formalized IRC Section 108 functions with #eval.
-/
-- Examples verifying the implementation

def exampleYear : TaxYear := { year := 2023, h_valid := by simp }

def exampleDischarge : DischargeIndebtedness := {
  amount := 10000,
  category := DischargeCategory.Insolvency,
  year := exampleYear
}

def exampleStatus : TaxpayerStatus := {
  insolvency_amount := 4000,
  is_c_corporation := false,
  filing_status := FilingStatus.Single,
  nol := 5000,
  general_business_credit := 1000,
  minimum_tax_credit := 0,
  capital_loss_carryover := 0,
  basis_of_property := 100000,
  passive_activity_loss_carryover := 0,
  foreign_tax_credit_carryover := 0
}

def exampleElections : TaxpayerElections := {}

-- Calculate excluded amount
-- Expected: min(10000, 4000) = 4000
#eval excludedAmount exampleDischarge exampleStatus exampleElections

-- Calculate reduced attributes
-- Excluded amount is 4000.
-- NOL reduction: min(5000, 4000) = 4000. Remaining excluded: 0.
-- New NOL: 5000 - 4000 = 1000.
-- Other attributes should be unchanged.
#eval (reduceAttributes (excludedAmount exampleDischarge exampleStatus exampleElections) exampleStatus).nol
#eval (reduceAttributes (excludedAmount exampleDischarge exampleStatus exampleElections) exampleStatus).general_business_credit

def exampleDischargeTitle11 : DischargeIndebtedness := {
  amount := 10000,
  category := DischargeCategory.Title11,
  year := exampleYear
}

-- Title 11 exclusion
-- Expected: 10000 (full amount)
#eval excludedAmount exampleDischargeTitle11 exampleStatus exampleElections

-- Attribute reduction for Title 11
-- Excluded: 10000
-- NOL reduction: min(5000, 10000) = 5000. Remaining: 5000.
-- New NOL: 0.
-- GBC reduction: min(1000, 5000 / 3) = min(1000, 1666) = 1000.
-- Used GBC equivalent: 1000 * 3 = 3000. Remaining: 5000 - 3000 = 2000.
-- New GBC: 0.
-- Basis reduction: min(100000, 2000) = 2000. Remaining: 0.
-- New Basis: 100000 - 2000 = 98000.
#eval (reduceAttributes (excludedAmount exampleDischargeTitle11 exampleStatus exampleElections) exampleStatus).nol
#eval (reduceAttributes (excludedAmount exampleDischargeTitle11 exampleStatus exampleElections) exampleStatus).general_business_credit
#eval (reduceAttributes (excludedAmount exampleDischargeTitle11 exampleStatus exampleElections) exampleStatus).basis_of_property

/-
NEW: Test cases for QualifiedRealPropertyBusiness to verify the fix for Issue #24
-/

-- Test Case 1: C Corporation (Should Get Zero)
def testCCorp : DischargeIndebtedness := {
  amount := 100000,
  category := DischargeCategory.QualifiedRealPropertyBusiness,
  year := exampleYear,
  outstanding_principal := 150000,
  property_fmv := 80000
}

def testCCorpStatus : TaxpayerStatus := {
  insolvency_amount := 50000,
  is_c_corporation := true,
  filing_status := FilingStatus.Single,
  nol := 0,
  general_business_credit := 0,
  minimum_tax_credit := 0,
  capital_loss_carryover := 0,
  basis_of_property := 0,
  passive_activity_loss_carryover := 0,
  foreign_tax_credit_carryover := 0,
  depreciable_real_property_basis := 120000
}

-- Expected: 0 (C corps ineligible per §108(a)(1)(D))
-- Old (WRONG) code: 50000 (used insolvency amount)
#eval excludedAmount testCCorp testCCorpStatus exampleElections

-- Test Case 2: S Corporation with Depreciable Basis as Binding Limit
def testSCorp : DischargeIndebtedness := {
  amount := 100000,
  category := DischargeCategory.QualifiedRealPropertyBusiness,
  year := exampleYear,
  outstanding_principal := 150000,  -- Principal
  property_fmv := 80000             -- FMV
  -- Principal - FMV = 70000 (limitation A)
}

def testSCorpStatus : TaxpayerStatus := {
  insolvency_amount := 120000,
  is_c_corporation := false,
  filing_status := FilingStatus.Single,
  nol := 0,
  general_business_credit := 0,
  minimum_tax_credit := 0,
  capital_loss_carryover := 0,
  basis_of_property := 0,
  passive_activity_loss_carryover := 0,
  foreign_tax_credit_carryover := 0,
  depreciable_real_property_basis := 60000  -- Limitation B (BINDING)
}

-- Expected: 60000 (limited by basis, which is less than principal-FMV of 70000)
-- Old (WRONG) code: 100000 (no limitations applied)
#eval excludedAmount testSCorp testSCorpStatus exampleElections

-- Test Case 3: Partnership - Principal-FMV Limit Binding
def testPartnership : DischargeIndebtedness := {
  amount := 100000,
  category := DischargeCategory.QualifiedRealPropertyBusiness,
  year := exampleYear,
  outstanding_principal := 110000,
  property_fmv := 85000
  -- Principal - FMV = 25000 (limitation A - BINDING)
}

def testPartnershipStatus : TaxpayerStatus := {
  insolvency_amount := 80000,
  is_c_corporation := false,
  filing_status := FilingStatus.Single,
  nol := 0,
  general_business_credit := 0,
  minimum_tax_credit := 0,
  capital_loss_carryover := 0,
  basis_of_property := 0,
  passive_activity_loss_carryover := 0,
  foreign_tax_credit_carryover := 0,
  depreciable_real_property_basis := 90000  -- Higher than 25000, so not binding
}

-- Expected: 25000 (limited by principal-FMV)
-- Old (WRONG) code: 100000 (no limitations)
#eval excludedAmount testPartnership testPartnershipStatus exampleElections

-- Test Case 4: Edge case - property_fmv > outstanding_principal (underwater = 0)
def testUnderwaterZero : DischargeIndebtedness := {
  amount := 50000,
  category := DischargeCategory.QualifiedRealPropertyBusiness,
  year := exampleYear,
  outstanding_principal := 100000,
  property_fmv := 120000  -- FMV > principal, so limitA = max(0, 100000-120000) = 0
}

def testUnderwaterZeroStatus : TaxpayerStatus := {
  insolvency_amount := 60000,
  is_c_corporation := false,
  filing_status := FilingStatus.Single,
  nol := 0,
  general_business_credit := 0,
  minimum_tax_credit := 0,
  capital_loss_carryover := 0,
  basis_of_property := 0,
  passive_activity_loss_carryover := 0,
  foreign_tax_credit_carryover := 0,
  depreciable_real_property_basis := 80000
}

-- Expected: 0 (limitA is 0 because property value exceeds debt)
#eval excludedAmount testUnderwaterZero testUnderwaterZeroStatus exampleElections

/-
NEW: Verification theorems for QualifiedRealPropertyBusiness fix
-/

/--
Theorem: C corporations are ineligible for QualifiedRealPropertyBusiness exclusion.
IRC §108(a)(1)(D): "in the case of a taxpayer OTHER THAN A C CORPORATION"
-/
theorem c_corp_ineligible_qrpb (d : DischargeIndebtedness) (s : TaxpayerStatus) (e : TaxpayerElections) :
  d.category = DischargeCategory.QualifiedRealPropertyBusiness →
  s.is_c_corporation = true →
  excludedAmount d s e = 0 := by
  intro h_cat h_ccorp
  unfold excludedAmount
  simp [h_cat, h_ccorp]

/--
Theorem: Non-C corporations' QualifiedRealPropertyBusiness exclusion is limited by
both §108(c)(2) limitations (principal-FMV and depreciable basis).
-/
theorem non_c_corp_qrpb_limited (d : DischargeIndebtedness) (s : TaxpayerStatus) (e : TaxpayerElections) :
  d.category = DischargeCategory.QualifiedRealPropertyBusiness →
  s.is_c_corporation = false →
  excludedAmount d s e ≤ d.amount ∧
  excludedAmount d s e ≤ max 0 (d.outstanding_principal - d.property_fmv) ∧
  excludedAmount d s e ≤ s.depreciable_real_property_basis := by
  intro h_cat h_not_ccorp
  unfold excludedAmount
  simp [h_cat, h_not_ccorp]
  constructor
  · apply Int.min_le_left
  constructor
  · apply le_trans
    · apply Int.min_le_right
    · apply Int.min_le_left
  · apply le_trans
    · apply Int.min_le_right
    · apply Int.min_le_right

/-
Theorem stating that if the excluded amount is fully absorbed by the NOL, then the General Business Credit is not reduced, assuming non-negative values.
-/
/--
Theorem: If the excluded amount is fully absorbed by the Net Operating Loss (NOL),
then the General Business Credit (and subsequent attributes) are not reduced.
Assumes non-negative attributes and excluded amount.
-/
theorem attributes_untouched_if_fully_absorbed_by_nol (excluded : Currency) (s : TaxpayerStatus) :
  excluded ≥ 0 →
  s.general_business_credit ≥ 0 →
  s.nol ≥ excluded →
  (reduceAttributes excluded s).general_business_credit = s.general_business_credit := by
    intros h_excluded_nonneg h_gbc_nonneg h_nol_ge_excluded
    simp [reduceAttributes, h_excluded_nonneg, h_gbc_nonneg, h_nol_ge_excluded];
    exact min_eq_right h_gbc_nonneg