/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: c733566e-f570-4ea8-afa4-da687f07301d
-/

/-
Formalization of IRC Section 62 (Adjusted Gross Income).
This module defines the `Currency` type, `TaxpayerData` structure, and the `calculateAGI` function
according to the specifications of IRC §62. It includes the specific deductions listed in the statute,
such as trade and business deductions, reimbursed employee expenses, and the specific $250 limit
on educator expenses.
The module also includes theorems verifying the correctness of the calculation, such as:
- `agi_le_gross_income`: AGI is less than or equal to gross income (assuming valid deductions).
- `educator_deduction_bounded`: The educator expense deduction never exceeds $250.
- `agi_linear_gross_income`: AGI scales linearly with gross income additions.
- `example_agi_correct`: A concrete example verifying the calculation logic.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
Define basic types for US Tax Code formalization: Currency, TaxYear, and FilingStatus.
-/
/-- Currency amount in cents or smallest unit, represented as an integer. -/
def Currency := Int

/-- Represents a tax year, which must be 1913 or later (inception of modern US income tax). -/
structure TaxYear where
  year : Nat
  h_valid : year ≥ 1913
  deriving DecidableEq

/-- Filing status for a taxpayer. -/
inductive FilingStatus
  | Single                         -- IRC §1(c)
  | MarriedFilingJointly          -- IRC §1(a)
  | MarriedFilingSeparately       -- IRC §1(d)
  | HeadOfHousehold               -- IRC §1(b)
  | QualifyingWidower             -- IRC §2(b)
  | Estate                         -- IRC §1(e)(1)
  | Trust                          -- IRC §1(e)(2)
  deriving Repr, DecidableEq, Inhabited

/-
Define Repr instance for Currency and TaxpayerData structure.
-/
instance : Repr Currency := inferInstanceAs (Repr Int)

/--
Structure representing the financial data of a taxpayer relevant to IRC §62.
This includes Gross Income and various specific deductions.
-/
structure TaxpayerData where
  /-- Total Gross Income before any deductions. -/
  grossIncome : Currency
  /-- (1) Trade and business deductions (non-employee). -/
  tradeBusinessDeductions : Currency
  /-- (2)(A) Reimbursed expenses of employees. -/
  reimbursedEmployeeExpenses : Currency
  /-- (2)(B) Expenses of qualified performing artists. -/
  performingArtistExpenses : Currency
  /-- (2)(C) Expenses of state/local officials paid on fee basis. -/
  stateOfficialExpenses : Currency
  /-- (2)(D) Expenses of eligible educators (subject to $250 limit logic). -/
  educatorExpenses : Currency
  /-- (2)(E) Expenses of reserve component members of Armed Forces. -/
  reservistExpenses : Currency
  /-- (3) Losses from sale or exchange of property. -/
  propertyLosses : Currency
  /-- (4) Deductions attributable to rents and royalties. -/
  rentRoyaltyDeductions : Currency
  /-- (5) Deductions of life tenants and income beneficiaries. -/
  lifeTenantDeductions : Currency
  /-- (6) Pension, profit-sharing, and annuity plans of self-employed individuals. -/
  selfEmployedPensionDeductions : Currency
  /-- (7) Retirement savings (IRA) deductions. -/
  iraDeductions : Currency
  /-- Other deductions allowed by Section 62 (catch-all for truncated text). -/
  otherSection62Deductions : Currency
  deriving Repr

/-
Add arithmetic and order instances for Currency to allow +, -, min, and numeric literals.
-/
instance : Add Currency := inferInstanceAs (Add Int)
instance : Sub Currency := inferInstanceAs (Sub Int)
instance : LinearOrder Currency := inferInstanceAs (LinearOrder Int)
instance (n : Nat) : OfNat Currency n := inferInstanceAs (OfNat Int n)

/-
Define the educator expense limit and the AGI calculation function.
-/
/--
The limit for educator expenses deduction under IRC §62(a)(2)(D).
Assumed to be in the same units as Currency (e.g., dollars).
-/
def educatorExpenseLimit : Currency := 250

/--
Calculates the Adjusted Gross Income (AGI) based on IRC §62.
AGI = Gross Income - Deductions allowed by §62.
-/
def calculateAGI (data : TaxpayerData) : Currency :=
  let d1 := data.tradeBusinessDeductions
  let d2a := data.reimbursedEmployeeExpenses
  let d2b := data.performingArtistExpenses
  let d2c := data.stateOfficialExpenses
  -- (2)(D) Limit educator expenses to $250
  let d2d := min data.educatorExpenses educatorExpenseLimit
  let d2e := data.reservistExpenses
  let d3 := data.propertyLosses
  let d4 := data.rentRoyaltyDeductions
  let d5 := data.lifeTenantDeductions
  let d6 := data.selfEmployedPensionDeductions
  let d7 := data.iraDeductions
  let other := data.otherSection62Deductions

  let totalDeductions := d1 + d2a + d2b + d2c + d2d + d2e + d3 + d4 + d5 + d6 + d7 + other
  data.grossIncome - totalDeductions

/-
Define validDeductions predicate and state theorem that AGI <= Gross Income given valid deductions.
-/
/--
Predicate to check if all deductions in TaxpayerData are non-negative.
This is a reasonable assumption for financial data where deductions represent positive amounts to be subtracted.
-/
def validDeductions (data : TaxpayerData) : Prop :=
  data.tradeBusinessDeductions ≥ 0 ∧
  data.reimbursedEmployeeExpenses ≥ 0 ∧
  data.performingArtistExpenses ≥ 0 ∧
  data.stateOfficialExpenses ≥ 0 ∧
  data.educatorExpenses ≥ 0 ∧
  data.reservistExpenses ≥ 0 ∧
  data.propertyLosses ≥ 0 ∧
  data.rentRoyaltyDeductions ≥ 0 ∧
  data.lifeTenantDeductions ≥ 0 ∧
  data.selfEmployedPensionDeductions ≥ 0 ∧
  data.iraDeductions ≥ 0 ∧
  data.otherSection62Deductions ≥ 0

/--
Theorem: If all deductions are non-negative, the Adjusted Gross Income (AGI)
will be less than or equal to the Gross Income.
-/
theorem agi_le_gross_income (data : TaxpayerData) (h : validDeductions data) :
  calculateAGI data ≤ data.grossIncome := by
  unfold calculateAGI;
  -- Since all the deductions are non-negative, their minimum is also non-negative.
  apply Int.le.intro;
  swap;
  exact ( data.tradeBusinessDeductions + data.reimbursedEmployeeExpenses + data.performingArtistExpenses + data.stateOfficialExpenses + Min.min data.educatorExpenses educatorExpenseLimit + data.reservistExpenses + data.propertyLosses + data.rentRoyaltyDeductions + data.lifeTenantDeductions + data.selfEmployedPensionDeductions + data.iraDeductions + data.otherSection62Deductions ).natAbs;
  rw [ Int.natAbs_of_nonneg ( h |> fun h => by
    cases h ; aesop;
    exact add_nonneg ( add_nonneg ( add_nonneg ( add_nonneg ( add_nonneg ( add_nonneg ( add_nonneg ( add_nonneg ( add_nonneg ( add_nonneg ( add_nonneg left left_1 ) left_2 ) left_3 ) ( le_min left_4 ( by decide ) ) ) left_5 ) left_6 ) left_7 ) left_8 ) left_9 ) left_10 ) right ) ] ; ring

/-
Define an example taxpayer for demonstration purposes.
-/
/--
Example taxpayer data to demonstrate the AGI calculation.
This taxpayer has $100,000 gross income and various deductions.
Note that educator expenses are $300, which should be capped at $250.
-/
def exampleTaxpayer : TaxpayerData := {
  grossIncome := 10000000, -- $100,000.00
  tradeBusinessDeductions := 500000, -- $5,000.00
  reimbursedEmployeeExpenses := 100000, -- $1,000.00
  performingArtistExpenses := 0,
  stateOfficialExpenses := 0,
  educatorExpenses := 30000, -- $300.00 (should be capped at $250.00)
  reservistExpenses := 0,
  propertyLosses := 200000, -- $2,000.00
  rentRoyaltyDeductions := 0,
  lifeTenantDeductions := 0,
  selfEmployedPensionDeductions := 0,
  iraDeductions := 500000, -- $5,000.00
  otherSection62Deductions := 0
}

/-
Verify the AGI calculation for the example taxpayer.
-/
/--
Theorem: The AGI for the example taxpayer is 8,699,750 cents ($86,997.50).
This verifies the calculation logic, including the educator expense cap.
-/
theorem example_agi_correct : calculateAGI exampleTaxpayer = 8699750 := by
  rfl

/-
Prove that the educator expense deduction is bounded by the limit.
-/
/--
Theorem: The deduction amount for educator expenses contributed to the total deductions
is always less than or equal to the limit (250), regardless of the input amount.
-/
theorem educator_deduction_bounded (data : TaxpayerData) :
  min data.educatorExpenses educatorExpenseLimit ≤ educatorExpenseLimit := by
  exact min_le_right _ _

/-
Prove that AGI increases linearly with gross income.
-/
/--
Theorem: Increasing gross income by a non-negative amount `k` increases AGI by `k`.
This demonstrates the linearity of the AGI calculation with respect to gross income.
-/
theorem agi_linear_gross_income (data : TaxpayerData) (k : Currency) :
  calculateAGI { data with grossIncome := data.grossIncome + k } = calculateAGI data + k := by
                  unfold calculateAGI;
                  unfold Currency; norm_num; ring;