/-
This file was edited by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 39a46481-425d-4f13-9d45-91d39c57cbcf

Aristotle encountered an error processing this file. The team has been notified.

-/


import Mathlib

def Currency := Int

structure TaxYear where
  year : Nat
  h_valid : year ≥ 1913
  deriving DecidableEq

inductive FilingStatus
  | Single
  | MarriedFilingJointly
  | MarriedFilingSeparately
  | HeadOfHousehold
  | QualifyingWidower
  | Estate
  | Trust
  deriving Repr, DecidableEq, Inhabited

/-!
# IRC Section 48 - Energy credit

This file formalizes IRC §48 (Energy credit).

## References
- [26 USC §48](https://www.law.cornell.edu/uscode/text/26/48)

## Summary
   Quick search by citation:
   Title
   Section
   Go!
   26 U.S. Code § 48 - Energy credit
   U.S. Code
   Notes
   Authorities (CFR)
   prev
   |
   next
   (a)
   Energy credit
   (1)
   In general
   For purposes of section 46, except as provided in paragraphs (1)(B), (2)(B), and (3)(B) of subsection (c), the energy credit for any taxable year is the energy percentage of the basis of each
   energy property
   placed in service during such taxable year.
   (2)
   Energy percentage
   (A)
   In general
   Except as provided in paragraphs (6) and (7), the energy percentage is—
   (i)
   6 percent in the case of—
   (I)
   qualified fuel cell property
   ,
   (II)
   energy property
   described in clause (i) or (iii) of paragraph (3)(A) but only with respect to property the construction of which begins before
   January 1, 2025
   ,
   (III)
   energy property
   described in paragraph (3)(A)(ii),
   (IV)
   qualified small wind energy property
   ,
   (V)
   waste energy recovery property
   ,
   (VI)
   energy storage technology
   ,
   (VII)
   qualified biogas property
   ,
   (VIII)
   microgrid controllers
   , and
   (IX)
   energy property
   described in clauses (v) and (vii) of paragraph (3)(A), and
   (ii)
   in the case of any
   energy property
   to which clause (i) does not apply, 0 percent.
   (B)
   Coordination with rehabilitation credit
   The energy percentage shall not apply to that portion of the basis of any property which is attributable to qualified rehabilitation expenditures.
   (C)
   Nonapplication of increases to energy percentage
   For purposes of
   energy property
   described in subparagraph (A)(ii), the energy percentage applicable to such property pursuant to such subparagraph shall not be increased or otherwise adjusted by any provision of this section.
   (3)
   Energy property
   For purposes of this subpart, the term “
   energy property
   ” means any property—
   (A)
   which is—
   (i)
   equipment which uses solar energy to generate electricity, to heat or cool (or provide hot water for use in) a structure, or to provide solar process heat, excepting property used to generate energy for the purposes of heating a swimming pool,
   (ii)
   equipment which uses solar energy to illuminate the inside of a structure using fiber-optic distributed sunlight, or electrochromic glass which uses electricity to change its light transmittance properties in order to heat or cool a structure, but only with respect to property the construction of which begins before
   January 1, 2025
   ,
   (iii)
   equipment used to produce, distribute, or use energy derived from a geothermal deposit (within the meaning of
   section 613(e)(2)
   ), but only, in the case of electricity generated by geothermal power, up to (but not including) the electrical transmission stage,
   (iv)
   qualified fuel cell property
   or
   qualified microturbine property
   ,
   (v)
   combined heat and power system property
   ,
   (vi)
   qualified small wind energy property
   ,
   (vii)
   equipment which uses the ground or ground water as a thermal energy source to heat a structure or as a thermal energy sink to cool a structure, but only with respect to property the construction of which begins before
   January 1, 2035
   ,
   (viii)
   waste energy recovery property
   ,
   (ix)
   energy storage technology
   ,
   (x)
   qualified biogas property
   , or
   (xi)
   microgrid controllers
   ,
   (B)
   (i)
   the construction, reconstruction, or erection of which is completed by the taxpayer, or
   (ii)
   which is acquired by the taxpayer if the original use of such property commences with the taxpayer,
   (C)
   with respect to which depreciation (or amortization in lieu of depreciation) is allowable, and
   (D)
   which meets the performance and quality standards (if any) which—
   (i)
   have been prescribed by the Secretary by regulations (after consultation with the Secretary of Energy), and
   (ii)
   are in effect at the time of the acquisition of the property.
   Such term shall not include any property which is part of a facility the production from which is allowed as a credit under
   section 45
   for the taxable year or any prior taxable year.
   (4)
   Special rule for property financed by tax-exempt bonds
   Rules similar to the rule under
   section 45(b)(3)
   shall apply for purposes of this section.
   (5)
   Election to treat qualified facilities as energy property
   (A)
   In general
   In the case of any
   qualified property
   which is part of a
   qualified investment credit facility
   —
   (i)
   such property shall be treated as
   energy property
   for purposes of this section, and
   (ii)
   the energy percentage with respect to such property shall be 6 percent.
   (B)
   Denial of production credit
   No credit shall be allowed under
   section 45
   for any taxable year with respect to any
   qualified investment credit facility.
   (C)
   Qualified investment credit facility
   For purposes of this paragraph, the term “
   qualified investment credit facility
   ” means any facility—
   (i)
   which is a qualified facility (within the meaning of
   section 45
   ) described in paragraph (1), (2), (3), (4), (6), (7), (9), or (11) of section 45(d),
   (ii)
   which is placed in service after 2008 and the construction of which begins before
   January 1, 2025
   , and
   (iii)
   with respect to which—
   (I)
   no credit has been allowed under section 45, and
   (II)
   the taxpayer makes an irrevocable election to have this paragraph apply.
   (D)
   Qualified property
   For purposes of this paragraph, the term “
   qualified property
   ” means property—
   (i)
   which is—
   (I)
   tangible personal property, or
   (II)
   other tangible property (not including a building or its structural components), but only if such property is used as an integral part of the
   qualified investment credit facility
   ,
   (ii)
   with respect to which depreciation (or amortization in lieu of depreciation) is allowable,
   (iii)
   which is constructed, reconstructed, erected, or acquired by the taxpayer, and
   (iv)
   the original use of which commences with the taxpayer.
   (E)
   Phaseout of credit for wind facilities
   In the case of any facility using wind to produce electricity which is placed in service before
   January 1, 2022
   , and treated as
   energy property
   by reason of this paragraph, the amount of the credit determined under this section (determined after the application of paragraphs (1) and (2) and without regard to this subparagraph) shall be reduced by—
   (i)
   in the case of any facility the construction of which begins after
   December 31, 2016
   , and before
   January 1, 2018
   , 20 percent,
   (ii)
   in the case of any facility the construction of which begins after
   December 31, 2017
   , and before
   January 1, 2019
   , 40 percent,
   (iii)
   in the case of any facility the construction of which begins after
   December 31, 2018
   , and before
   January 1, 2020
   , 60 percent, and
   (iv)
   in the case of any facility the construction of which begins after
   December 31, 2019
   , and before
   January 1, 2022
   , 40 percent.
   (F)
   Qualified offshore wind facilities
   (i)
   In general
   In the case of any
   qualified offshore wind facility
   , subparagraph (E) shall not apply.
   (ii)
   Qualified offshore wind facility
   For purposes of this subparagraph, the term “
   qualified offshore wind facility
   ” means a qualified facility (within the meaning of section 45) described in paragraph (1) of section 45(d) (determined without regard to any date by which the construction of the facility is required to begin) which is located in the inland navigable waters of the United States or in the coastal waters of the United States.
   (6)
   Phaseout for certain energy property
   In the case of any
   qualified fuel cell property
   , qualified small wind property, or
   energy property
   described in clause (i) or clause (ii) of paragraph (3)(A) the construction of which begins after
   December 31, 2019
   , and which is placed in service before
   January 1, 2022
   , the energy percentage determined under paragraph (2) shall be equal to 26 percent.
   (7)
   Phaseout for certain energy property
   In the case of any
   energy property
   described in clause (vii) of paragraph (3)(A), the energy percentage determined under paragraph (2) shall be equal to—
   (A)
   in the case of any property the construction of which begins before
   January 1, 2033
   , and which is placed in service after
   December 31, 2021
   , 6 percent,
   (B)
   in the case of any property the construction of which begins after
   December 31, 2032
   , and before
   January 1, 2034
   , 5.2 percent, and
   (C)
   in the case of any property the construction of which begins after
   December 31, 2033
   , and before
   January 1, 2035
   , 4.4 percent.
   (8)
   Interconnection property
   (A)
   In general
   For purposes of determining the credit under subsection (a),
   energy property
   shall include amounts paid or incurred by the taxpayer for
   qualified interconnection property
   in connection with the installation of
   energy property
   (as defined in paragraph (3)) which has a maximum net output of not greater than 5 megawatts (as measured in alternating current), to provide for the transmission or distribution of the electricity produced or stored by such property, and which are properly chargeable to the capital account of the taxpayer.
   (B)
   Qualified interconnection property
   The term “
   qualified interconnection property
   ” means, with respect to an
   energy project
   which is not a
   microgrid controller,
   any tangible property—
   (i)
   which is part of an addition, modification, or upgrade to a transmission or distribution system which is required at or beyond the point at which the
   energy project
   interconnects to such transmission or distribution system in order to accommodate such interconnection,
   (ii)
   either—
   (I)
   which is constructed, reconstructed, or erected by the taxpayer, or
   (II)
   for which the cost with respect to the construction, reconstruction, or erection of such property is paid or incurred by such taxpayer, and
   (iii)
   the original use of which, pursuant to an
   interconnection agreement
   , commences with a
   utility.
   (C)
   Interconnection agreement
   The term “
   interconnection agreement
   ” means an agreement with a
   utility
   for the purposes of interconnecting the
   energy property
   owned by such taxpayer to the transmission or distribution system of such
   utility.
   (D)
   Utility
   For purposes of this paragraph, the term “
   utility
   ” means the owner or operator of an electrical transmission or distribution system which is subject to the regulatory authority of a State or political subdivision thereof, any agency or instrumentality of the United States, a public service or public
   utility
   commission or other similar body of any State or political subdivision thereof, or the governing or ratemaking body of an electric cooperative.
   (E)
   Special rule for interconnection property
   In the case of expenses paid or incurred for interconnection property, amounts otherwise chargeable to capital account with respect to such expenses shall be reduced under rules similar to the rules of section 50(c).
   (9)
   Increased credit amount for energy projects
   (A)
   In general
   (i)
   Rule
   In the case of any
   energy project
   which satisfies the requirements of subparagraph (B), the amount of the credit determined under this subsection (determined after the application of paragraphs (1) through (8) and paragraph (15) and without regard to this clause) shall be equal to such amount multiplied by 5.
   (ii)
   Energy project defined
   For purposes of this subsection, the term “
   energy project
   ” means a project consisting of one or more energy properties that are part of a single project.
   (B)
   Project requirements
   A project meets the requirements of this subparagraph if it is one of the following:
   (i)
   A project with a maximum net output of less than 1 megawatt of electrical (as measured in alternating current) or thermal energy.
   (ii)
   A project the construction of which begins before the date that is 60 days after the Secretary publishes guidance with respect to the requirements of paragraphs (10)(A) and (11).
   (iii)
   A project which satisfies the requirements of paragraphs (10)(A) and (11).
   (10)
   Prevailing wage requirements
   (A)
   In general
   The requirements described in this subparagraph with respect to any
   energy project
   are that the taxpayer shall ensure that any laborers and mechanics employed by the taxpayer or any contractor or subcontractor in—
   (i)
   the construction of such
   energy project
   , and
   (ii)
   for the 5-year period beginning on the date such project is originally placed in service, the alteration or repair of such project,
   shall be paid wages at rates not less than the prevailing rates for construction, alteration, or repair of a similar character in the locality in which such project is located as most recently determined by the Secretary of Labor, in accordance with subchapter IV of chapter
   31
   of title 40, United States Code. Subject to subparagraph (C), for purposes of any determination under paragraph (9)(A)(i) for the taxable year in which the
   energy project
   is placed in service, the taxpayer shall be deemed to satisfy the requirement under clause (ii) at the time such project is placed in service.
   (B)
   Correction and penalty related to failure to satisfy wage requirements
   Rules similar to the rules of
   section 45(b)(7)(B)
   shall apply.
   (C)
   Recapture
   The Secretary shall, by regulations or other guidance, provide for recapturing the benefit of any increase in the credit allowed under this subsection by reason of this paragraph with respect to any project which does not satisfy the requirements under subparagraph (A) (after application of subparagraph (B)) for the period described in clause (ii) of subparagraph (A) (but which does not cease to be investment credit property within the meaning of
   section 50(a)
   ). The period and percentage of such recapture shall be determined under rules similar to the rules of section 50(a).
   (11)
   Apprenticeship requirements
   Rules similar to the rules of
   section 45(b)(8)
   shall apply.
   (12)
   Domestic content bonus credit amount
   (A)
   In general
   In the case of any
   energy project
   which satisfies the requirement under subparagraph (B), for purposes of applying paragraph (2) with respect to such property, the energy percentage shall be increased by the applicable credit rate increase.
   (B)
   Requirement
   Rules similar to the rules of
   section 45(b)(9)(B)
   shall apply.
   (C)
   Applicable credit rate increase
   For purposes of subparagraph (A), the applicable credit rate increase shall be—
   (i)
   in the case of an
   energy project
   which does not satisfy the requirements of paragraph (9)(B), 2 percentage points, and
   (ii)
   in the case of an
   energy project
   which satisfies the requirements of paragraph (9)(B), 10 percentage points.
   (13)
   Phaseout for elective payment
   In the case of a taxpayer making an election under
   section 6417
   with respect to a credit under this section, rules similar to the rules of section 45(b)(10) shall apply.
   (14)
   Increase in credit rate for energy communities
   (A)
   In general
   In the case of any
   energy project
   that is placed in service within an energy community (as defined in section 45(b)(11)(B), as applied by substituting “
   energy project
   ” for “qualified facility” each place it appears), for purposes of applying paragraph (2) with respect to
   energy property
   which is part of such project, the energy percentage shall be increased by the applicable credit rate increase.
   (B)
   Applicable credit rate increase
   For purposes of subparagraph (A), the applicable credit rate increase shall be equal to—
   (i)
   in the case of any
   energy project
   which does not satisfy the requirements of paragraph (9)(B), 2 percentage points, and
   (ii)
   in the case of any
   energy project
   which satisfies the requirements of paragraph (9)(B), 10 percentage points.
   (15)
   Election to treat clean hydrogen production facilities as energy property
   (A)
   In general
   In the case of any
   qualified property
   (as defined in paragraph (5)(D)) which is part of a
   specified clean hydrogen production facility
   —
   (i)
   such property shall be treated as
   energy property
   for purposes of this section, and
   (ii)
   the energy percentage with respect to such property is—
   (I)
   in the case of a facility which is designed and reasonably expected to produce
   qualified clean hydrogen
   which is described in a subparagraph (A) of section 45V(b)(2), 1.2 percent,
   (II)
   in the case of a facility which is designed and reasonably expected to produce
   qualified clean hydrogen
   which is described in a subparagraph (B) of such section, 1.5 percent,
   (III)
   in the case of a facility which is designed and reasonably expected to produce
   qualified clean hydrogen
   which is described in a subparagraph (C) of such section, 2 percent, and
   (IV)
   in the case of a facility which is designed and reasonably expected to produce
   qualified clean hydrogen
   which is described in subparagraph (D) of such section, 6 percent.
   (B)
   Denial of production credit
   No credit shall be allowed under section 45V or section 45Q for any taxable year with respect to any
   specified clean hydrogen production facility
   or any carbon capture equipment included at such facility.
   (C)
   Specified clean hydrogen production facility
   For purposes of this paragraph, the term “
   specified clean hydrogen production facility
   ” means any
   qualified clean hydrogen
   production facility (as defined in
   section 45V(c)(3)
   )—
   (i)
   which is placed in service after
   December 31, 2022
   ,
   (ii)
   with respect to which—
   (I)
   no credit has been allowed under
   section 45V
   or 45Q, and
   (II)
   the taxpayer makes an irrevocable election to have this paragraph apply, and
   (iii)
   for which an unrelated third party has verified (in such form or manner as the Secretary may prescribe) that such facility produces hydrogen through a process which results in lifecycle greenhouse gas emissions which are consistent with the hydrogen that such facility was designed and expected to produce under subparagraph (A)(ii).
   (D)
   Qualified clean hydrogen
   For purposes of this paragraph, the term “
   qualified clean hydrogen
   ” has the meaning given such term by section 45V(c)(2).
   (E)
   Regulations
   The Secretary shall issue such regulations or other guidance as the Secretary determines necessary to carry out the purposes of this section, including regulations or other guidance which recaptures so much of any credit allowed under this section as exceeds the amount of the credit which would have been allowed if the expected production were consistent with the actual verified production (or all of the credit so allowed in the absence of such verification).
   (16)
   Regulations and guidance
   The Secretary shall issue such regulations or other guidance as the Secretary determines necessary to carry out the purposes of this subsection, including regulations or other guidance which provides for requirements for recordkeeping or information reporting for purposes of administering the requirements of this subsection.
   (b)
   Certain progress expenditure rules made applicable
   Rules similar to the rules of subsections (c)(4) and (d) of section 46 (as in effect on the day before the date of the enactment of the
   Revenue Reconciliation Act of 1990
   ) shall apply for purposes of subsection (a).
   (c)
   Definitions
   For purposes of this section—
   (1)
   Qualified fuel cell property
   (A)
   In general
   The term “
   qualified fuel cell property
   ” means a
   fuel cell power plant
   which—
   (i)
   has a nameplate capacity of at least 0.5 kilowatt (1 kilowatt in the case of a
   fuel cell power plant
   with a linear generator assembly) of electricity using an electrochemical or electromechanical process, and
   (ii)
   has an electricity-only generation efficiency greater than 30 percent.
   (B)
   Limitation
   In the case of
   qualified fuel cell property
   placed in service during the taxable year, the credit otherwise determined under subsection (a) for such year with respect to such property shall not exceed an amount equal to $1,500 for each 0.5 kilowatt of capacity of such property.
   (C)
   Fuel cell power plant
   The term “
   fuel cell power plant
   ” means an integrated system comprised of a fuel cell stack assembly, or linear generator assembly, and associated balance of plant components which converts a fuel into electricity using electrochemical or electromechanical means.
   (D)
   Linear generator assembly
   The term “linear generator assembly” does not include any assembly which contains rotating parts.
   (E)
   Termination
   The term “
   qualified fuel cell property
   ” shall not include any property the construction of which does not begin before
   January 1, 2025
   .
   (2)
   Qualified microturbine property
   (A)
   In general
   The term “
   qualified microturbine property
   ” means a
   stationary microturbine power plant
   which—
   (i)
   has a nameplate capacity of less than 2,000 kilowatts, and
   (ii)
   has an electricity-only generation efficiency of not less than 26 percent at International Standard Organization conditions.
   (B)
   Limitation
   In the case of
   qualified microturbine property
   placed in service during the taxable year, the credit otherwise determined under subsection (a) for such year with respect to such property shall not exceed an amount equal to $200 for each kilowatt of capacity of such property.
   (C)
   Stationary microturbine power plant
   The term “
   stationary microturbine power plant
   ” means an integrated system comprised of a gas turbine engine, a combustor, a recuperator or regenerator, a generator or alternator, and associated balance of plant components which converts a fuel into electricity and thermal energy. Such term also includes all secondary components located between the existing infrastructure for fuel delivery and the existing infrastructure for power distribution, including equipment and controls for meeting relevant power standards, such as voltage, frequency, and power factors.
   (D)
   Termination
   The term “
   qualified microturbine property
   ” shall not include any property the construction of which does not begin before
   January 1, 2025
   .
   (3)
   Combined heat and power system property
   (A)
   Combined heat and power system property
   The term “
   combined heat and power system property
   ” means property comprising a system—
   (i)
   which uses the same energy source for the simultaneous or sequential generation of electrical power, mechanical shaft power, or both, in combination with the generation of steam or other forms of useful thermal energy (including heating and cooling applications),
   (ii)
   which produces—
   (I)
   at least 20 percent of its total useful energy in the form of thermal energy which is not used to produce electrical or mechanical power (or combination thereof), and
   (II)
   at least 20 percent of its total useful energy in the form of electrical or mechanical power (or combination thereof),
   (iii)
   the energy efficiency percentage of which exceeds 60 percent, and
   (iv)

-- [Content truncated - key provisions above]

-- TODO: Add type definitions
-- TODO: Add main functions
-- TODO: Add theorems to prove