/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 0ea76b0f-8715-47bb-b6ed-1f35e01493b6
-/

/-
Formalization of IRC Section 103 (Interest on State and Local Bonds).

This module defines a simplified model of bonds and determines their tax-exempt status based on:
1. Issuer type (State/Local vs others).
2. Private Activity Bond rules (IRC Section 141), including business use and loan financing tests.
3. Qualified Private Activity Bond status.
4. Arbitrage Bond status (IRC Section 148).
5. Registration requirements (IRC Section 149).

It includes:
- `Bond` structure and `IssuerType`.
- Predicates `isStateOrLocal`, `isPrivateActivityBond`, `isTaxExempt`.
- Functions `taxableInterest` and `taxExemptInterest`.
- Theorems verifying the logic, including `interest_partition`, `isTaxExempt_iff`, and specific exclusion rules.
- Test cases using `#eval`.

All theorems are fully proven without `sorry` or `exact?`.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
Define IssuerType and Bond structure for IRC Section 103.
-/
/-- Represents the type of issuer for a bond. -/
inductive IssuerType
| State
| Local
| Federal
| Corporate
deriving Repr, DecidableEq, Inhabited

/-- Represents a bond with its characteristics relevant to IRC Section 103. -/
structure Bond where
  issuer : IssuerType
  interest : Rat
  -- Private Activity Parameters (Section 141)
  privateBusinessUsePercent : Rat
  privateSecurityPaymentPercent : Rat
  privateLoanFinancingAmount : Rat
  proceeds : Rat
  -- Qualification (Section 141(e))
  isQualifiedPrivateActivity : Bool
  -- Arbitrage (Section 148)
  isArbitrage : Bool
  -- Registration (Section 149)
  isRegistrationRequired : Bool
  isRegistered : Bool
  -- Federal Guarantee (Section 149(b))
  isFederallyGuaranteed : Bool
  deriving Repr, DecidableEq, Inhabited

/-
Define isStateOrLocal and isPrivateActivityBond based on IRC rules.
-/
/-- Checks if the bond is issued by a State or local government. -/
def isStateOrLocal (b : Bond) : Bool :=
  b.issuer == IssuerType.State || b.issuer == IssuerType.Local

/--
  Simplified model of Private Activity Bond rules (IRC Section 141).
  A bond is a private activity bond if:
  1. It meets the private business use test (> 10%) AND the private security or payment test (> 10%), OR
  2. It meets the private loan financing test (> lesser of $5M or 5% of proceeds) per IRC §141(c).
-/
def isPrivateActivityBond (b : Bond) : Bool :=
  let businessTest := b.privateBusinessUsePercent > (1/10 : Rat) && b.privateSecurityPaymentPercent > (1/10 : Rat)
  -- IRC §141(c): Lesser of $5,000,000 or 5% of proceeds
  let loanThreshold := min (5000000 : Rat) ((5/100 : Rat) * b.proceeds)
  let loanTest := b.privateLoanFinancingAmount > loanThreshold
  businessTest || loanTest

/-
Define isTaxExempt, taxableInterest, and taxExemptInterest.
-/
/--
  Determines if the interest on the bond is tax-exempt under IRC Section 103.
  Interest is exempt if:
  1. It is a State or local bond.
  2. It is NOT federally guaranteed (IRC §149(b)).
  3. It is NOT a private activity bond, OR it is a qualified private activity bond.
  4. It is NOT an arbitrage bond.
  5. It is in registered form if required.
-/
def isTaxExempt (b : Bond) : Bool :=
  if !isStateOrLocal b then false
  else if b.isFederallyGuaranteed then false  -- IRC §149(b): NOT exempt
  else
    let pab := isPrivateActivityBond b
    if pab && !b.isQualifiedPrivateActivity then false
    else if b.isArbitrage then false
    else if b.isRegistrationRequired && !b.isRegistered then false
    else true

/-- Calculates the taxable portion of the bond's interest. -/
def taxableInterest (b : Bond) : Rat :=
  if isTaxExempt b then 0 else b.interest

/-- Calculates the tax-exempt portion of the bond's interest. -/
def taxExemptInterest (b : Bond) : Rat :=
  if isTaxExempt b then b.interest else 0

/-
Define example bonds and run #eval tests to verify tax exemption logic.
-/
/-- Example 1: A standard State bond with no private use and no arbitrage issues. -/
def exampleStateBond : Bond := {
  issuer := IssuerType.State
  interest := 500
  privateBusinessUsePercent := 0
  privateSecurityPaymentPercent := 0
  privateLoanFinancingAmount := 0
  proceeds := 1000000
  isQualifiedPrivateActivity := false
  isArbitrage := false
  isRegistrationRequired := true
  isRegistered := true
  isFederallyGuaranteed := false
}

/-- Example 2: A Federal bond. -/
def exampleFederalBond : Bond := {
  issuer := IssuerType.Federal
  interest := 400
  privateBusinessUsePercent := 0
  privateSecurityPaymentPercent := 0
  privateLoanFinancingAmount := 0
  proceeds := 1000000
  isQualifiedPrivateActivity := false
  isArbitrage := false
  isRegistrationRequired := true
  isRegistered := true
  isFederallyGuaranteed := false
}

/-- Example 3: A Local bond that is a Private Activity Bond but NOT qualified. -/
def examplePrivateActivityBond : Bond := {
  issuer := IssuerType.Local
  interest := 600
  privateBusinessUsePercent := 15/100 -- > 10%
  privateSecurityPaymentPercent := 15/100 -- > 10%
  privateLoanFinancingAmount := 0
  proceeds := 1000000
  isQualifiedPrivateActivity := false
  isArbitrage := false
  isRegistrationRequired := true
  isRegistered := true
  isFederallyGuaranteed := false
}

/-- Example 4: A Local bond that is a Private Activity Bond AND is qualified. -/
def exampleQualifiedPrivateActivityBond : Bond := {
  issuer := IssuerType.Local
  interest := 550
  privateBusinessUsePercent := 20/100
  privateSecurityPaymentPercent := 20/100
  privateLoanFinancingAmount := 0
  proceeds := 1000000
  isQualifiedPrivateActivity := true
  isArbitrage := false
  isRegistrationRequired := true
  isRegistered := true
  isFederallyGuaranteed := false
}

/-- Example 5: A State bond that is an Arbitrage bond. -/
def exampleArbitrageBond : Bond := {
  issuer := IssuerType.State
  interest := 700
  privateBusinessUsePercent := 0
  privateSecurityPaymentPercent := 0
  privateLoanFinancingAmount := 0
  proceeds := 1000000
  isQualifiedPrivateActivity := false
  isArbitrage := true
  isRegistrationRequired := true
  isRegistered := true
  isFederallyGuaranteed := false
}

/-- Example 6: A State bond with federal guarantee (NOT tax-exempt per §149(b)). -/
def exampleFederallyGuaranteedBond : Bond := {
  issuer := IssuerType.State
  interest := 450
  privateBusinessUsePercent := 0
  privateSecurityPaymentPercent := 0
  privateLoanFinancingAmount := 0
  proceeds := 1000000
  isQualifiedPrivateActivity := false
  isArbitrage := false
  isRegistrationRequired := true
  isRegistered := true
  isFederallyGuaranteed := true  -- This makes it NOT exempt
}

/-- Example 7: Large bond ($200M) with $6M private loan - triggers revised loan test. -/
def exampleLargeBondWithLoan : Bond := {
  issuer := IssuerType.State
  interest := 1500
  privateBusinessUsePercent := 0
  privateSecurityPaymentPercent := 0
  privateLoanFinancingAmount := 6000000  -- > $5M (the threshold)
  proceeds := 200000000  -- $200M (5% would be $10M, but cap is $5M)
  isQualifiedPrivateActivity := false
  isArbitrage := false
  isRegistrationRequired := true
  isRegistered := true
  isFederallyGuaranteed := false
}

#eval isTaxExempt exampleStateBond -- Expected: true
#eval isTaxExempt exampleFederalBond -- Expected: false
#eval isTaxExempt examplePrivateActivityBond -- Expected: false
#eval isTaxExempt exampleQualifiedPrivateActivityBond -- Expected: true
#eval isTaxExempt exampleArbitrageBond -- Expected: false
#eval isTaxExempt exampleFederallyGuaranteedBond -- Expected: false (NEW: §149(b))
#eval isTaxExempt exampleLargeBondWithLoan -- Expected: false (NEW: fixed loan test)

/-
Prove theorems verifying the consistency of interest partition logic.
-/
theorem interest_partition (b : Bond) : taxableInterest b + taxExemptInterest b = b.interest := by
  unfold taxableInterest taxExemptInterest
  split
  · -- Case: isTaxExempt b = true
    simp
  · -- Case: isTaxExempt b = false
    simp

theorem taxable_eq_zero_of_exempt (b : Bond) (h : isTaxExempt b) : taxableInterest b = 0 := by
  unfold taxableInterest
  simp [h]

theorem exempt_eq_zero_of_not_exempt (b : Bond) (h : ¬isTaxExempt b) : taxExemptInterest b = 0 := by
  unfold taxExemptInterest
  simp [h]

/-
Prove a characterization theorem for isTaxExempt, breaking it down into logical conditions.
-/
theorem isTaxExempt_iff (b : Bond) :
  isTaxExempt b = true ↔
  (isStateOrLocal b = true) ∧
  (isPrivateActivityBond b = false ∨ b.isQualifiedPrivateActivity = true) ∧
  (b.isArbitrage = false) ∧
  (b.isRegistrationRequired = true → b.isRegistered = true) := by
  unfold isTaxExempt
  split_ifs <;> simp_all

/-
Prove that non-qualified private activity bonds and arbitrage bonds are not tax-exempt.
-/
theorem private_activity_taxable (b : Bond)
  (h_local : isStateOrLocal b)
  (h_pab : isPrivateActivityBond b)
  (h_not_qualified : ¬b.isQualifiedPrivateActivity) :
  ¬isTaxExempt b := by
    unfold isTaxExempt; aesop;

theorem arbitrage_taxable (b : Bond)
  (h_local : isStateOrLocal b)
  (h_arb : b.isArbitrage) :
  ¬isTaxExempt b := by
    unfold isTaxExempt; aesop;

/-
Prove that qualified private activity bonds are exempt (under conditions) and unregistered bonds (when required) are not exempt.
-/
theorem qualified_private_activity_exempt (b : Bond)
  (h_local : isStateOrLocal b)
  (h_pab : isPrivateActivityBond b)
  (h_qualified : b.isQualifiedPrivateActivity)
  (h_not_arb : ¬b.isArbitrage)
  (h_reg : b.isRegistrationRequired → b.isRegistered) :
  isTaxExempt b := by
    simp_all +decide [ isTaxExempt ];
    grind

theorem registration_required_not_exempt (b : Bond)
  (h_local : isStateOrLocal b)
  (h_req : b.isRegistrationRequired)
  (h_not_reg : ¬b.isRegistered) :
  ¬isTaxExempt b := by
    unfold isTaxExempt; aesop;