/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: a9813d5b-7d16-44cc-b5a7-477086ae8612
-/

/-
Formalization of IRC Section 11 in Lean 4.
Includes definitions for Corporation, TaxYear, and Currency.
Implements the tax calculation logic for IRC §11(a)-(d).
Provides theorems verifying the tax calculation for domestic and foreign corporations,
as well as handling of exceptions under §11(c).
Includes executable examples for verification.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

-- Common definitions (inline these if needed)
def Currency := Int
structure TaxYear where
  year : Nat
  h_valid : year ≥ 1913
  deriving DecidableEq

inductive FilingStatus
  | Single
  | MarriedFilingJointly
  | MarriedFilingSeparately
  | HeadOfHousehold
  | QualifyingWidower
  deriving DecidableEq, Repr

/-
Define instances for Currency to allow arithmetic.
Define the Corporation structure and the tax calculation function for IRC Section 11.
Also prove that for a standard domestic corporation, the tax is 21% of income.
-/
-- Enable arithmetic on Currency
instance : Add Currency := inferInstanceAs (Add Int)
instance : Sub Currency := inferInstanceAs (Sub Int)
instance : Mul Currency := inferInstanceAs (Mul Int)
instance : Div Currency := inferInstanceAs (Div Int)
instance : LT Currency := inferInstanceAs (LT Int)
instance : LE Currency := inferInstanceAs (LE Int)
instance : DecidableEq Currency := inferInstanceAs (DecidableEq Int)
instance : Inhabited Currency := inferInstanceAs (Inhabited Int)
instance (n : Nat) : OfNat Currency n := inferInstanceAs (OfNat Int n)

-- Allow coercion from Nat to Currency (useful for literals and Nat values)
instance : Coe Nat Currency := ⟨fun n => Int.ofNat n⟩

structure Corporation where
  name : String
  is_foreign : Bool
  subject_to_sec_594 : Bool -- mutual savings banks conducting life insurance business
  subject_to_subchapter_L : Bool -- insurance companies
  subject_to_subchapter_M : Bool -- regulated investment companies and real estate investment trusts
  deriving DecidableEq, Repr

/-- IRC §11(b) Amount of tax -/
def tax_rate_percent : Currency := 21

/-- IRC §11(b) Calculation -/
def calculate_base_tax (income : Currency) : Currency :=
  (income * tax_rate_percent) / 100

/-- IRC §11 -/
def section_11_tax (c : Corporation) (year : TaxYear) (taxable_income : Currency) : Option Currency :=
  if c.subject_to_sec_594 ∨ c.subject_to_subchapter_L ∨ c.subject_to_subchapter_M then
    -- IRC §11(c) Exceptions
    some 0
  else if c.is_foreign then
    -- IRC §11(d) Foreign corporations
    -- "apply only as provided by section 882"
    none
  else
    -- IRC §11(a) and (b)
    some (calculate_base_tax taxable_income)

theorem section_11_domestic_tax (c : Corporation) (y : TaxYear) (i : Currency) :
  ¬c.is_foreign → ¬c.subject_to_sec_594 → ¬c.subject_to_subchapter_L → ¬c.subject_to_subchapter_M →
  section_11_tax c y i = some ((i * 21) / 100) := by
  intros hf h594 hL hM
  unfold section_11_tax calculate_base_tax tax_rate_percent
  simp [hf, h594, hL, hM]

/-
Theorems verifying the handling of foreign corporations and exceptions in IRC §11.
-/
theorem section_11_foreign_corporation (c : Corporation) (y : TaxYear) (i : Currency) :
  c.is_foreign →
  ¬c.subject_to_sec_594 → ¬c.subject_to_subchapter_L → ¬c.subject_to_subchapter_M →
  section_11_tax c y i = none := by
  intros hf h594 hL hM
  unfold section_11_tax
  simp [hf, h594, hL, hM]

theorem section_11_exception_594 (c : Corporation) (y : TaxYear) (i : Currency) :
  c.subject_to_sec_594 →
  section_11_tax c y i = some 0 := by
  intros h
  unfold section_11_tax
  simp [h]

theorem section_11_exception_subchapter_L (c : Corporation) (y : TaxYear) (i : Currency) :
  c.subject_to_subchapter_L →
  section_11_tax c y i = some 0 := by
  intros h
  unfold section_11_tax
  simp [h]

theorem section_11_exception_subchapter_M (c : Corporation) (y : TaxYear) (i : Currency) :
  c.subject_to_subchapter_M →
  section_11_tax c y i = some 0 := by
  intros h
  unfold section_11_tax
  simp [h]

/-
Define example corporations and evaluate their tax liability under IRC §11.
-/
-- Examples
def example_domestic_corp : Corporation := {
  name := "Acme Corp",
  is_foreign := false,
  subject_to_sec_594 := false,
  subject_to_subchapter_L := false,
  subject_to_subchapter_M := false
}

def example_foreign_corp : Corporation := {
  name := "Global Ltd",
  is_foreign := true,
  subject_to_sec_594 := false,
  subject_to_subchapter_L := false,
  subject_to_subchapter_M := false
}

def example_insurance_corp : Corporation := {
  name := "SafeLife Inc",
  is_foreign := false,
  subject_to_sec_594 := false,
  subject_to_subchapter_L := true,
  subject_to_subchapter_M := false
}

def tax_year_2023 : TaxYear := { year := 2023, h_valid := by simp }

-- Test cases
#eval section_11_tax example_domestic_corp tax_year_2023 100000 -- Should be 21000
#eval section_11_tax example_domestic_corp tax_year_2023 100 -- Should be 21
#eval section_11_tax example_foreign_corp tax_year_2023 100000 -- Should be none
#eval section_11_tax example_insurance_corp tax_year_2023 100000 -- Should be some 0