/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: f78db2a3-97f4-4b74-9f3a-e0bd72ecfa56
-/

/-
Formalization of IRC Section 55 (Alternative Minimum Tax).

This module defines the basic types and calculation functions for the Alternative Minimum Tax (AMT) as described in 26 U.S. Code § 55. It includes:
- Type definitions for `Currency`, `TaxYear`, and `FilingStatus`.
- Calculation functions for:
  - Alternative Minimum Taxable Income (AMTI)
  - Taxable Excess
  - Tentative Minimum Tax (TMT) for non-corporate taxpayers (including the specific threshold for married filing separately)
  - Tentative Minimum Tax for corporations
  - The final Alternative Minimum Tax
- Theorems verifying that:
  - AMT is always non-negative.
  - TMT for non-corporate taxpayers is always non-negative.
  - AMT is zero if the regular tax (plus Sec 59A tax) exceeds the TMT.

Note: The capital gains rates in §55(b)(3) are not implemented in this version, as noted in the comments. The exemption amounts are treated as inputs to the `taxable_excess` function, as their specific values are defined in §55(d) which was not fully provided.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
Define basic types for IRC Section 55 formalization including Currency, TaxYear, and FilingStatus.
-/
-- Common definitions
def Currency := Int

structure TaxYear where
  year : Nat
  h_valid : year ≥ 1913
  deriving DecidableEq

inductive FilingStatus
  | Single
  | MarriedFilingJointly
  | MarriedFilingSeparately
  | HeadOfHousehold
  | QualifyingWidower
  deriving DecidableEq, Repr

/-
Define instances for Currency and calculation functions for IRC Section 55.
-/
instance : Add Currency := inferInstanceAs (Add Int)
instance : Sub Currency := inferInstanceAs (Sub Int)
instance : Mul Currency := inferInstanceAs (Mul Int)
instance : Div Currency := inferInstanceAs (Div Int)
instance : LE Currency := inferInstanceAs (LE Int)
instance : LT Currency := inferInstanceAs (LT Int)
instance : DecidableEq Currency := inferInstanceAs (DecidableEq Int)
instance : Max Currency := inferInstanceAs (Max Int)
instance : Min Currency := inferInstanceAs (Min Int)
instance (n : Nat) : OfNat Currency n := inferInstanceAs (OfNat Int n)
instance : Inhabited Currency := inferInstanceAs (Inhabited Int)
instance : LinearOrder Currency := inferInstanceAs (LinearOrder Int)

/-- IRC §55(b)(1)(D) - Alternative Minimum Taxable Income -/
def alternative_minimum_taxable_income
  (taxable_income : Currency)
  (adjustments : Currency)
  (preferences : Currency) : Currency :=
  taxable_income + adjustments + preferences

/-- IRC §55(b)(1)(B) - Taxable Excess -/
def taxable_excess (amti : Currency) (exemption_amount : Currency) : Currency :=
  max 0 (amti - exemption_amount)

/-- Helper for IRC §55(b)(1)(A) threshold -/
def tmt_threshold (status : FilingStatus) : Currency :=
  match status with
  | FilingStatus.MarriedFilingSeparately => 87500
  | _ => 175000

/-- IRC §55(b)(1)(A) - Tentative Minimum Tax for Noncorporate Taxpayers
    Note: This implements the regular calculation. Paragraph (3) provides a cap based on capital gains which is not implemented here. -/
def tentative_minimum_tax_noncorporate
  (status : FilingStatus)
  (excess : Currency)
  (foreign_tax_credit : Currency) : Currency :=
  let threshold := tmt_threshold status
  let lower_bracket := min excess threshold
  let upper_bracket := max 0 (excess - threshold)
  let tax_before_credit := (lower_bracket * 26) / 100 + (upper_bracket * 28) / 100
  max 0 (tax_before_credit - foreign_tax_credit)

/-- IRC §55(b)(2) - Tentative Minimum Tax for Corporations -/
def tentative_minimum_tax_corporation
  (is_applicable : Bool)
  (adjusted_financial_statement_income : Currency)
  (foreign_tax_credit : Currency) : Currency :=
  if is_applicable then
    let tax_before_credit := (adjusted_financial_statement_income * 15) / 100
    max 0 (tax_before_credit - foreign_tax_credit)
  else
    0

/-- IRC §55(a) - Alternative Minimum Tax Imposed -/
def alternative_minimum_tax
  (tentative_min_tax : Currency)
  (regular_tax : Currency)
  (tax_59A : Currency) : Currency :=
  max 0 (tentative_min_tax - (regular_tax + tax_59A))

/-
Theorem: The Alternative Minimum Tax is always non-negative.
-/
/-- Theorem: The Alternative Minimum Tax is always non-negative. -/
theorem amt_nonnegative
  (tmt : Currency)
  (reg_tax : Currency)
  (tax_59A : Currency) :
  alternative_minimum_tax tmt reg_tax tax_59A ≥ 0 := by
  exact le_max_left _ _

/-
Theorem: The Tentative Minimum Tax for non-corporate taxpayers is always non-negative.
-/
/-- Theorem: The Tentative Minimum Tax for non-corporate taxpayers is always non-negative. -/
theorem tmt_noncorporate_nonnegative
  (status : FilingStatus)
  (excess : Currency)
  (ftc : Currency) :
  tentative_minimum_tax_noncorporate status excess ftc ≥ 0 := by
  unfold tentative_minimum_tax_noncorporate; aesop;

/-
Theorem: If the regular tax (plus section 59A tax) is greater than or equal to the tentative minimum tax, then the alternative minimum tax is zero.
-/
/-- Theorem: If the regular tax (plus section 59A tax) is greater than or equal to the
    tentative minimum tax, then the alternative minimum tax is zero. -/
theorem amt_zero_if_regular_tax_exceeds_tmt
  (tmt : Currency)
  (reg_tax : Currency)
  (tax_59A : Currency)
  (h : reg_tax + tax_59A ≥ tmt) :
  alternative_minimum_tax tmt reg_tax tax_59A = 0 := by
  -- By definition of alternative minimum tax, we have:
  unfold alternative_minimum_tax;
  simp +zetaDelta at *;
  exact Int.sub_nonpos_of_le h