/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 6e86af46-b51d-46ec-942a-afd04a31b9d9
-/

/-
Formalization of IRC Section 101: Certain Death Benefits.
This module defines the types and functions necessary to calculate exclusions from gross income for life insurance proceeds payable by reason of death.
It covers:
- §101(a): General rule for exclusion of death benefits.
- §101(a)(2): Transfer for valuable consideration rule and its exceptions.
- §101(c): Inclusion of interest payments.
- §101(d): Proration of amounts held by an insurer.
Key definitions include `PolicyTransfer`, `InsurancePayout`, `InterestAgreement`, and `DeferredPaymentAgreement`.
Theorems verify the correctness of the logic against the statutory text.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
Basic definitions for IRC Section 101 formalization including Currency, TaxYear, and FilingStatus.
-/
-- Common definitions
def Currency := Int

structure TaxYear where
  year : Nat
  h_valid : year ≥ 1913
  deriving DecidableEq

inductive FilingStatus
  | Single                         -- IRC §1(c)
  | MarriedFilingJointly          -- IRC §1(a)
  | MarriedFilingSeparately       -- IRC §1(d)
  | HeadOfHousehold               -- IRC §1(b)
  | QualifyingWidower             -- IRC §2(b)
  | Estate                         -- IRC §1(e)(1)
  | Trust                          -- IRC §1(e)(2)
  deriving Repr, DecidableEq, Inhabited

/-
Defines the PolicyTransfer structure to represent the transfer of a life insurance contract, including fields for consideration, basis carryover, and reportable policy sales.
-/
/-- Represents a transfer of a life insurance contract. -/
structure PolicyTransfer where
  /-- Whether the transfer was for valuable consideration. -/
  isForValuableConsideration : Bool
  /-- The actual value of consideration paid. -/
  consideration : Currency
  /-- Premiums and other amounts paid by the transferee after the transfer. -/
  premiumsAndOtherAmounts : Currency
  /-- Whether the contract has a basis determined by reference to the transferor's basis (e.g., gift). §101(a)(2)(A) -/
  basisCarryover : Bool
  /-- Whether the transfer is to the insured, a partner, a partnership, or a corporation. §101(a)(2)(B) -/
  toInsuredOrPartnerOrCorp : Bool
  /-- Whether the transfer is a reportable policy sale. §101(a)(3) -/
  isReportablePolicySale : Bool
  deriving DecidableEq

/-
Defines the InsurancePayout structure to represent the details of a life insurance payout, including the amount received, whether it was due to death, and any transfer details.
-/
/-- Represents the details of a life insurance payout. -/
structure InsurancePayout where
  /-- The total amount received. -/
  amountReceived : Currency
  /-- Whether the amount is paid by reason of the death of the insured. -/
  reasonIsDeath : Bool
  /-- Details of the last transfer, if any. -/
  lastTransfer : Option PolicyTransfer
  deriving DecidableEq

/-
Adds typeclass instances to treat Currency as Int for addition, ordering, and numeric literals.
-/
instance : Add Currency := inferInstanceAs (Add Int)
instance : LinearOrder Currency := inferInstanceAs (LinearOrder Int)
instance {n} : OfNat Currency n := inferInstanceAs (OfNat Int n)

/-
Calculates the exclusion amount under IRC §101(a), handling the general rule (exclusion of death benefits), the transfer for valuable consideration rule (limiting exclusion to consideration + premiums), and exceptions to the transfer for value rule (basis carryover, transfers to insured/partner/corp, and reportable policy sales).
-/
/-- Calculates the amount excluded from gross income under §101(a). -/
def calculateExclusionSection101a (payout : InsurancePayout) : Currency :=
  if ¬payout.reasonIsDeath then
    0
  else
    match payout.lastTransfer with
    | none => payout.amountReceived
    | some transfer =>
      if ¬transfer.isForValuableConsideration then
        payout.amountReceived
      else
        -- Transfer for valuable consideration
        let limit := transfer.consideration + transfer.premiumsAndOtherAmounts
        let useLimit :=
          if transfer.isReportablePolicySale then
            true
          else if transfer.basisCarryover || transfer.toInsuredOrPartnerOrCorp then
            false
          else
            true
        
        if useLimit then
          min payout.amountReceived limit
        else
          payout.amountReceived

/-
Defines the InterestAgreement structure and calculates the amount to be included in gross income under IRC §101(c), which mandates that interest payments on excluded amounts are taxable.
-/
/-- Represents an agreement to pay interest on amounts excluded under §101(a). -/
structure InterestAgreement where
  /-- The amount of interest paid or accrued. -/
  interestPaid : Currency
  /-- Whether the amount is held under an agreement to pay interest. -/
  isHeldUnderAgreement : Bool
  deriving DecidableEq

/-- Calculates the amount included in gross income under §101(c). -/
def calculateInclusionSection101c (agreement : InterestAgreement) : Currency :=
  if agreement.isHeldUnderAgreement then
    agreement.interestPaid
  else
    0

/-
Adds a Div instance for Currency, allowing division operations by treating Currency as Int.
-/
instance : Div Currency := inferInstanceAs (Div Int)

/-
Defines a coercion from Nat to Currency using Int.ofNat.
-/
instance : Coe Nat Currency := ⟨Int.ofNat⟩

/-
Defines the DeferredPaymentAgreement structure, which includes the amount held by the insurer, the payment period in years, and the amount received in the current year.
-/
/-- Represents an agreement to pay life insurance proceeds at a date later than death. -/
structure DeferredPaymentAgreement where
  /-- The amount held by the insurer (value as of date of death). §101(d)(2) -/
  amountHeld : Currency
  /-- The number of years over which payments are to be made. -/
  paymentPeriodYears : Nat
  /-- The total amount received by the beneficiary in the current tax year. -/
  amountReceivedThisYear : Currency
  /-- Ensure the payment period is positive to avoid division by zero. -/
  h_period_pos : paymentPeriodYears > 0
  deriving DecidableEq

/-
Calculates the annual exclusion amount under IRC §101(d) by prorating the amount held by the insurer over the payment period.
-/
/-- Calculates the amount excluded from gross income under §101(d) for a given year. -/
def calculateExclusionSection101d (agreement : DeferredPaymentAgreement) : Currency :=
  let period : Currency := agreement.paymentPeriodYears
  let proratedAmount := agreement.amountHeld / period
  min agreement.amountReceivedThisYear proratedAmount

/-
Theorem: For a life insurance payout made by reason of death with no prior transfers, the amount excluded from gross income is equal to the total amount received.
-/
theorem exclusion_eq_amount_received_for_simple_death_benefit
  (payout : InsurancePayout)
  (h_death : payout.reasonIsDeath = true)
  (h_no_transfer : payout.lastTransfer = none) :
  calculateExclusionSection101a payout = payout.amountReceived := by
  unfold calculateExclusionSection101a; aesop

/-
Theorem: If a life insurance contract is transferred for valuable consideration and no exceptions apply (not a reportable policy sale, no basis carryover, not to insured/partner/corp), the exclusion is limited to the sum of consideration and premiums paid.
-/
theorem exclusion_limited_by_transfer_for_value
  (payout : InsurancePayout)
  (transfer : PolicyTransfer)
  (h_death : payout.reasonIsDeath = true)
  (h_transfer : payout.lastTransfer = some transfer)
  (h_valuable : transfer.isForValuableConsideration = true)
  (h_no_reportable : transfer.isReportablePolicySale = false)
  (h_no_carryover : transfer.basisCarryover = false)
  (h_no_partner : transfer.toInsuredOrPartnerOrCorp = false) :
  calculateExclusionSection101a payout = min payout.amountReceived (transfer.consideration + transfer.premiumsAndOtherAmounts) := by
  unfold calculateExclusionSection101a ; aesop

/-
Theorem: If a life insurance contract is transferred for valuable consideration but qualifies for an exception (basis carryover or transfer to insured/partner/corp) and is not a reportable policy sale, the full amount is excluded from gross income.
-/
theorem exclusion_full_for_exception_to_transfer_for_value
  (payout : InsurancePayout)
  (transfer : PolicyTransfer)
  (h_death : payout.reasonIsDeath = true)
  (h_transfer : payout.lastTransfer = some transfer)
  (h_valuable : transfer.isForValuableConsideration = true)
  (h_no_reportable : transfer.isReportablePolicySale = false)
  (h_exception : transfer.basisCarryover = true ∨ transfer.toInsuredOrPartnerOrCorp = true) :
  calculateExclusionSection101a payout = payout.amountReceived := by
  cases h_exception <;> unfold calculateExclusionSection101a <;> aesop

/-
Theorem: Interest payments held under an agreement are fully included in gross income.
-/
theorem interest_is_fully_included
  (agreement : InterestAgreement)
  (h_held : agreement.isHeldUnderAgreement = true) :
  calculateInclusionSection101c agreement = agreement.interestPaid := by
  exact if_pos h_held

/-
Documentation note outlining the coverage of the formalization and listing omitted sections as TODOs.
-/
/--
Formalization Coverage Notes for IRC §101:
- Covered:
  - §101(a): Proceeds of life insurance contracts payable by reason of death.
  - §101(a)(1): General rule.
  - §101(a)(2): Transfer for valuable consideration.
  - §101(a)(3): Exception to valuable consideration rules for commercial transfers.
  - §101(c): Interest payments.
  - §101(d): Payment of life insurance proceeds at a date later than death.
- Omitted / TODO:
  - §101(f): Proceeds of flexible premium contracts issued before January 1, 1985.
  - §101(j): Treatment of certain employer-owned life insurance contracts.
-/
def section101_coverage_notes : String := "See docstring for coverage details."