/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: df2ca0b6-0052-463a-991b-571d26520ed5
-/

/-
Formalization of the repeal of IRC Section 71 (Alimony), including the effective date logic based on execution and modification dates of divorce or separation instruments. Defines types for dates and instruments, implements the logic for determining if the repeal applies, and provides a function for the alimony inclusion amount (which is 0 if repealed). Includes theorems verifying the correctness of the repeal logic against the statutory text.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
Define the basic types and structures required for the formalization, including Currency, TaxYear, FilingStatus, and Date, along with comparison instances for Date.
-/
-- Common definitions
def Currency := Int

structure TaxYear where
  year : Nat
  h_valid : year ≥ 1913
  deriving DecidableEq, Repr

inductive FilingStatus
  | Single                         -- IRC §1(c)
  | MarriedFilingJointly          -- IRC §1(a)
  | MarriedFilingSeparately       -- IRC §1(d)
  | HeadOfHousehold               -- IRC §1(b)
  | QualifyingWidower             -- IRC §2(b)
  | Estate                         -- IRC §1(e)(1)
  | Trust                          -- IRC §1(e)(2)
  deriving Repr, DecidableEq, Inhabited

structure Date where
  year : Nat
  month : Nat
  day : Nat
  deriving DecidableEq, Repr, Ord

def Date.le (a b : Date) : Bool :=
  if a.year < b.year then true
  else if a.year > b.year then false
  else if a.month < b.month then true
  else if a.month > b.month then false
  else a.day <= b.day

instance : LE Date where
  le a b := Date.le a b

instance : DecidableRel (LE.le (α := Date)) :=
  fun a b => inferInstanceAs (Decidable (Date.le a b))

def Date.lt (a b : Date) : Bool :=
  if a.year < b.year then true
  else if a.year > b.year then false
  else if a.month < b.month then true
  else if a.month > b.month then false
  else a.day < b.day

instance : LT Date where
  lt a b := Date.lt a b

instance : DecidableRel (LT.lt (α := Date)) :=
  fun a b => inferInstanceAs (Decidable (Date.lt a b))

-- Specific dates mentioned in the text
def date_Dec_22_2017 : Date := ⟨2017, 12, 22⟩
def date_Dec_31_2018 : Date := ⟨2018, 12, 31⟩

/-
Define DivorceInstrument and the logic for determining if Section 71 is repealed based on execution and modification dates. Define alimonyInclusionAmount based on the repeal status. Fixed the literal 0 issue.
-/
structure DivorceInstrument where
  executionDate : Date
  modificationDate : Option Date
  modificationAdoptsRepeal : Bool
  deriving DecidableEq, Repr

-- IRC §71 Repeal Effective Date Logic
-- "Repeal applicable to any divorce or separation instrument ... executed after Dec. 31, 2018"
-- "and to such instruments executed on or before Dec. 31, 2018, and modified after Dec. 31, 2018, if the modification expressly provides..."
def isSection71Repealed (instr : DivorceInstrument) : Bool :=
  if instr.executionDate > date_Dec_31_2018 then
    true
  else
    match instr.modificationDate with
    | some modDate =>
      modDate > date_Dec_31_2018 && instr.modificationAdoptsRepeal
    | none => false

-- If Section 71 applies (is not repealed), alimony is included in gross income.
-- If repealed, it is not included (amount is 0).
-- This assumes the payment qualifies as alimony under the pre-repeal definition.
def alimonyInclusionAmount (instr : DivorceInstrument) (paymentAmount : Currency) : Currency :=
  if isSection71Repealed instr then
    (0 : Int)
  else
    paymentAmount

/-
Theorem: If a divorce instrument is executed after Dec 31, 2018, then Section 71 is repealed for it.
-/
theorem repeal_applies_post_2018 (instr : DivorceInstrument)
    (h : instr.executionDate > date_Dec_31_2018) :
    isSection71Repealed instr = true := by
  unfold isSection71Repealed; aesop;

/-
Theorem: If a divorce instrument is executed on or before Dec 31, 2018, but modified after Dec 31, 2018, and the modification expressly adopts the repeal, then Section 71 is repealed for it.
-/
theorem repeal_applies_modification (instr : DivorceInstrument)
    (h_exec : instr.executionDate ≤ date_Dec_31_2018)
    (h_mod_date : ∃ d, instr.modificationDate = some d ∧ d > date_Dec_31_2018)
    (h_adopts : instr.modificationAdoptsRepeal = true) :
    isSection71Repealed instr = true := by
  unfold isSection71Repealed; aesop

/-
Theorem: If a divorce instrument is executed on or before Dec 31, 2018, and has no modification, then Section 71 is not repealed for it.
-/
theorem repeal_does_not_apply_no_mod (instr : DivorceInstrument)
    (h_exec : instr.executionDate ≤ date_Dec_31_2018)
    (h_no_mod : instr.modificationDate = none) :
    isSection71Repealed instr = false := by
  unfold isSection71Repealed;
  rw [ show date_Dec_31_2018 = ⟨ 2018, 12, 31 ⟩ by rfl ] at * ; aesop;
  unfold instLTDate at * ; aesop;
  unfold instLEDate at * ; aesop;
  unfold Date.le Date.lt at * ; aesop;
  all_goals linarith;

/-
Theorem: If a divorce instrument is executed on or before Dec 31, 2018, modified after Dec 31, 2018, but the modification does not expressly adopt the repeal, then Section 71 is not repealed for it.
-/
theorem repeal_does_not_apply_mod_no_adopt (instr : DivorceInstrument)
    (h_exec : instr.executionDate ≤ date_Dec_31_2018)
    (h_mod : ∃ d, instr.modificationDate = some d ∧ d > date_Dec_31_2018)
    (h_no_adopt : instr.modificationAdoptsRepeal = false) :
    isSection71Repealed instr = false := by
  unfold isSection71Repealed;
  unfold instLTDate at * ; aesop;
  unfold instLEDate at * ; aesop;
  unfold Date.le at h_exec ; unfold Date.lt at * ; aesop;
  all_goals linarith