/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: bca44fa4-bbb9-4783-9563-f58cd229ff09
-/

/-
Formalization of IRC Section 199 based on the provided legal text.

This module includes:
1.  Basic type definitions for `Currency`, `TaxYear`, and `FilingStatus`.
2.  A structure `Section199Input` to capture the necessary data for the calculations.
3.  Implementation of the special rule for transportation costs of independent refiners under IRC §199(c)(3)(C), including the termination clause.
4.  Implementation of the special rule for Puerto Rico activities under IRC §199(d)(8), including the definition of "United States" and the W-2 wage limitation rule.
5.  A check for the applicability of Section 199 based on its repeal for tax years beginning after December 31, 2017.
6.  Theorems verifying the termination dates and conditions for these rules.

The formalization covers the specific subsections provided in the prompt: (c)(3)(C) and (d)(8), as well as the general repeal provision.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
Basic type definitions for IRC Section 199 formalization including Currency, TaxYear, and FilingStatus.
-/
-- Common definitions
def Currency := Int

structure TaxYear where
  year : Nat
  h_valid : year ≥ 1913
  deriving DecidableEq

inductive FilingStatus
  | Single
  | MarriedFilingJointly
  | MarriedFilingSeparately
  | HeadOfHousehold
  | QualifyingWidower
  deriving DecidableEq, Repr

/-
Adding necessary instances for Currency and TaxYear to make them usable. Correcting the syntax for OfNat.
-/
instance : Repr TaxYear where
  reprPrec t _ := repr t.year

instance : Repr Currency := inferInstanceAs (Repr Int)
instance : DecidableEq Currency := inferInstanceAs (DecidableEq Int)
instance : Add Currency := inferInstanceAs (Add Int)
instance : Sub Currency := inferInstanceAs (Sub Int)
instance : Mul Currency := inferInstanceAs (Mul Int)
instance : LE Currency := inferInstanceAs (LE Int)
instance : LT Currency := inferInstanceAs (LT Int)
instance {n} : OfNat Currency n := inferInstanceAs (OfNat Int n)

/-
Structure to hold input data for IRC Section 199 calculations.
-/
structure Section199Input where
  -- General info
  tax_year : TaxYear
  
  -- For (c)(3)(C)
  is_oil_refiner : Bool
  is_major_integrated_oil_company : Bool
  transportation_costs_properly_allocable : Currency

  -- For (d)(8)
  gross_receipts_from_puerto_rico : Currency
  all_pr_receipts_taxable_under_sec_1_or_11 : Bool
  w2_wages_with_pr_exclusion : Currency -- Normal W-2 wages
  w2_wages_without_pr_exclusion : Currency -- W-2 wages if we ignore 3401(a)(8)
  deriving DecidableEq, Repr

/-
Adding Div instance for Currency.
-/
instance : Div Currency := inferInstanceAs (Div Int)

/-
Function to calculate transportation costs under IRC §199(c)(3)(C), handling the independent refiner rule and its termination date. Retrying after adding Div instance.
-/
/--
IRC §199(c)(3)(C) Transportation costs of independent refiners
(i) In general: In the case of any taxpayer who is in the trade or business of refining crude oil and who is not a major integrated oil company... the amount allocated... for costs related to the transportation of oil shall be 25 percent of the amount properly allocable...
(ii) Termination: Clause (i) shall not apply to any taxable year beginning after December 31, 2021.
-/
def transportation_costs (input : Section199Input) : Currency :=
  -- Check termination date: applies only if year <= 2021
  if input.tax_year.year > 2021 then
    input.transportation_costs_properly_allocable
  else
    -- Check eligibility: refiner AND NOT major integrated oil company
    if input.is_oil_refiner ∧ ¬input.is_major_integrated_oil_company then
      (input.transportation_costs_properly_allocable * 25) / (100 : Currency)
    else
      input.transportation_costs_properly_allocable

/-
Functions to determine if Puerto Rico is included in 'United States' and to calculate W-2 wages accordingly, under IRC §199(d)(8).
-/
/--
IRC §199(d)(8) Treatment of activities in Puerto Rico
(A) In general: ... term "United States" shall include the Commonwealth of Puerto Rico.
(C) Termination: ... taxable years ... beginning after December 31, 2005, and before January 1, 2017.
-/
def is_puerto_rico_included (input : Section199Input) : Bool :=
  let year := input.tax_year.year
  -- Termination check: 2006 <= year <= 2016
  if year >= 2006 ∧ year <= 2016 then
    -- Condition: all receipts taxable under sec 1 or 11
    input.all_pr_receipts_taxable_under_sec_1_or_11
  else
    false

/--
IRC §199(d)(8)(B) Special rule for applying wage limitation
-/
def calculate_w2_wages (input : Section199Input) : Currency :=
  if is_puerto_rico_included input then
    input.w2_wages_without_pr_exclusion
  else
    input.w2_wages_with_pr_exclusion

/-
Function to check if Section 199 is applicable based on the repeal date (tax years beginning on or before Dec 31, 2017).
-/
/--
IRC Section 199 Repeal
Repeal applicable to taxable years beginning after Dec. 31, 2017.
-/
def is_section_199_applicable (year : TaxYear) : Bool :=
  year.year <= 2017

/-
Theorem: For tax years after 2021, transportation costs equal the properly allocable costs (termination of special rule). Retrying with simple sorry.
-/
theorem transportation_costs_after_2021 (input : Section199Input)
  (h : input.tax_year.year > 2021) :
  transportation_costs input = input.transportation_costs_properly_allocable := by
    exact if_pos h

/-
Theorem: The Puerto Rico inclusion rule does not apply to tax years before 2006 or after 2016.
-/
theorem puerto_rico_rule_termination (input : Section199Input)
  (h_before : input.tax_year.year < 2006 ∨ input.tax_year.year > 2016) :
  is_puerto_rico_included input = false := by
    -- We can use the hypothesis `h_before` to split into the two cases.
    cases h_before;
    · exact if_neg ( by aesop );
    · unfold is_puerto_rico_included; aesop;

/-
Theorem: Section 199 is not applicable for tax years after 2017.
-/
theorem section_199_repealed_after_2017 (year : TaxYear)
  (h : year.year > 2017) :
  is_section_199_applicable year = false := by
    exact if_neg h.not_le