/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 1c804c02-4930-41f0-a09a-7a27dbda3781
-/

/-
Formalization of IRC Section 59 including AMT Foreign Tax Credit, Optional 10-year Writeoff, and Apportionment of Differently Treated Items. Includes type definitions, calculation functions, and proven theorems about the properties of these calculations.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

-- Common definitions (inline these if needed)
def Currency := Int
structure TaxYear where
  year : Nat
  h_valid : year ≥ 1913
  deriving DecidableEq

inductive FilingStatus
  | Single
  | MarriedFilingJointly
  | MarriedFilingSeparately
  | HeadOfHousehold
  | QualifyingWidower
  deriving DecidableEq, Repr

-- Fix instances for Currency since it was defined as a def
instance : Repr Currency := inferInstanceAs (Repr Int)
instance : LinearOrder Currency := inferInstanceAs (LinearOrder Int)
instance : Add Currency := inferInstanceAs (Add Int)
instance : Sub Currency := inferInstanceAs (Sub Int)
instance : Mul Currency := inferInstanceAs (Mul Int)
instance : Div Currency := inferInstanceAs (Div Int)
instance : Mod Currency := inferInstanceAs (Mod Int)
instance (n : Nat) : OfNat Currency n := inferInstanceAs (OfNat Int n)
instance : Inhabited Currency := inferInstanceAs (Inhabited Int)

-- IRC §59(a) Alternative minimum tax foreign tax credit

structure AMTForeignTaxCreditInput where
  preCreditTentativeMinimumTax : Currency
  amti : Currency -- Alternative Minimum Taxable Income
  foreignSourceAMTI : Currency
  foreignSourceRegularTI : Currency
  foreignTaxesPaid : Currency
  simplifiedLimitationElection : Bool
  deriving Repr, DecidableEq

/--
Calculates the Alternative Minimum Tax Foreign Tax Credit under IRC §59(a).
Includes the logic for the simplified limitation election under §59(a)(3).
-/
def calculateAMTForeignTaxCredit (input : AMTForeignTaxCreditInput) : Currency :=
  if input.amti = 0 then 0 else
  let numerator :=
    if input.simplifiedLimitationElection then
      -- §59(a)(3)(A)(ii)(I): taxable income from sources without US but not in excess of AMTI
      min input.foreignSourceRegularTI input.amti
    else
      -- §59(a)(1)(B): Section 904 applied on basis of AMTI
      input.foreignSourceAMTI
  
  -- §59(a)(1)(A): pre-credit tentative minimum tax is the tax against which credit is taken
  -- Limitation formula: (Foreign Source Income / Total AMTI) * Tentative Minimum Tax
  let limitation := (numerator * input.preCreditTentativeMinimumTax) / input.amti
  
  -- The credit is the lesser of taxes paid and the limitation (standard §27/§904 principle)
  min input.foreignTaxesPaid limitation

instance : Repr TaxYear where
  reprPrec t _ := "TaxYear.mk " ++ repr t.year

def natToCurrency (n : Nat) : Currency := (n : Int)

-- IRC §59(e) Optional 10-year writeoff of certain tax preferences

inductive QualifiedExpenditureType
  | Circulation -- §173
  | ResearchAndExperimental -- §174(a)
  | IntangibleDrilling -- §263(c)
  | MiningExploration -- §616(a)
  | MiningDevelopment -- §617(a)
  | Other -- General 10-year case
  deriving Repr, DecidableEq

structure QualifiedExpenditure where
  amount : Currency
  yearIncurred : TaxYear
  type : QualifiedExpenditureType
  deriving Repr, DecidableEq

/--
Determines the writeoff period (in years) for a qualified expenditure under §59(e)(1) and (2).
-/
def writeoffPeriod (type : QualifiedExpenditureType) : Nat :=
  match type with
  | .Circulation => 3
  | .IntangibleDrilling => 5 -- 60 months = 5 years
  | _ => 10

/--
Calculates the deduction allowed for a specific tax year for a given qualified expenditure.
Returns 0 if the year is outside the writeoff period.
-/
def calculateWriteoffDeduction (expenditure : QualifiedExpenditure) (currentYear : TaxYear) : Currency :=
  let period := writeoffPeriod expenditure.type
  let yearsElapsed := currentYear.year - expenditure.yearIncurred.year
  if currentYear.year >= expenditure.yearIncurred.year && yearsElapsed < period then
    expenditure.amount / natToCurrency period
  else
    0

-- IRC §59(d) Apportionment of differently treated items

structure DifferentlyTreatedItem where
  description : String
  amount : Currency
  deriving Repr, DecidableEq

/--
Apportions a differently treated item between an entity and its participants/shareholders.
Returns a pair (entityAmount, participantsAmount).
ratioForEntity should be a percentage (0-100).
-/
def apportionItem (item : DifferentlyTreatedItem) (ratioForEntity : Nat) : Currency × Currency :=
  let ratio : Currency := natToCurrency ratioForEntity
  let hundred : Currency := natToCurrency 100
  let entityAmount := (item.amount * ratio) / hundred
  let participantsAmount := item.amount - entityAmount
  (entityAmount, participantsAmount)

/--
Theorem: The AMT Foreign Tax Credit is never negative (assuming inputs are non-negative).
-/
theorem amt_foreign_tax_credit_nonneg (input : AMTForeignTaxCreditInput)
  (h_pre : input.preCreditTentativeMinimumTax ≥ 0)
  (h_amti : input.amti > 0)
  (h_foreign_amti : input.foreignSourceAMTI ≥ 0)
  (h_foreign_reg : input.foreignSourceRegularTI ≥ 0)
  (h_taxes : input.foreignTaxesPaid ≥ 0) :
  calculateAMTForeignTaxCredit input ≥ 0 := by
  unfold calculateAMTForeignTaxCredit;
  aesop;
  · -- Since the numerator is a product of non-negative terms and the denominator is positive, the division is non-negative.
    apply Int.ediv_nonneg;
    · positivity;
    · -- Since AMTI is positive, it is also non-negative.
      exact le_of_lt h_amti;
  · -- Since the numerator is non-negative and the denominator is positive, their division is non-negative.
    apply Int.ediv_nonneg; exact mul_nonneg h_foreign_amti h_pre; exact h_amti.le

/--
Theorem: The writeoff deduction is zero if the current year is before the year incurred.
-/
theorem writeoff_deduction_before_incurred (exp : QualifiedExpenditure) (cy : TaxYear)
  (h : cy.year < exp.yearIncurred.year) :
  calculateWriteoffDeduction exp cy = 0 := by
  -- Since `cy.year < exp.yearIncurred.year`, the first condition `cy.year >= exp.yearIncurred.year` is false, so the result is zero.
  simp [calculateWriteoffDeduction, h]