/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 4cce11fa-6891-49c7-af2a-c9cf8011d7e1
-/

/-
Formalization of IRC Section 199 (Repealed) in Lean 4.

This module defines the data structures and calculation logic for the repealed IRC Section 199, specifically focusing on:
- Subsection (c)(3)(C): Transportation costs of independent refiners.
- Subsection (d)(8): Treatment of activities in Puerto Rico.

The formalization includes:
- `Currency` defined as `Int` for precise arithmetic.
- `TaxYear` and `FilingStatus` structures.
- `Section199Input` structure to capture all necessary taxpayer data.
- `transportation_costs_independent_refiners`: Calculates the allocable transportation costs, applying the 25% rule for independent refiners.
- `total_w2_wages`: Calculates W-2 wages, including Puerto Rico wages if the special rule applies.
- Theorems `transportation_costs_independent_refiners_correct` and `total_w2_wages_correct` verifying the logic against the statutory requirements.

Note: Section 199 was repealed by Pub. L. 115–97 for taxable years beginning after Dec. 31, 2017. A check `Section199_is_repealed` is included.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
Define the basic types for the IRC Section 199 formalization: Currency, TaxYear, and FilingStatus.
-/
-- Common definitions
def Currency := Int

structure TaxYear where
  year : Nat
  h_valid : year ≥ 1913
  deriving DecidableEq, Repr

inductive FilingStatus
  | Single
  | MarriedFilingJointly
  | MarriedFilingSeparately
  | HeadOfHousehold
  | QualifyingWidower
  deriving DecidableEq, Repr

/-
Define the input structure for Section 199 calculations, capturing fields for independent refiners and Puerto Rico activities.
-/
structure Section199Input where
  -- General info
  taxYear : TaxYear
  
  -- For (c)(3)(C) Independent Refiners
  in_business_of_refining_crude_oil : Bool
  is_major_integrated_oil_company : Bool
  oil_transportation_costs_allocable : Currency
  
  -- For (d)(8) Puerto Rico
  gross_receipts_from_puerto_rico : Currency
  all_puerto_rico_receipts_taxable_us : Bool -- taxable under section 1 or 11
  w2_wages_excluding_puerto_rico : Currency
  puerto_rico_wages : Currency
  deriving DecidableEq

/-
Define a function to check if Section 199 is repealed for a given tax year (repealed for years beginning after Dec 31, 2017).
-/
def Section199_is_repealed (year : TaxYear) : Bool :=
  year.year > 2017

/-
Define the calculation for transportation costs of independent refiners under Section 199(c)(3)(C), using a local variable to ensure the type is treated as Int.
-/
def transportation_costs_independent_refiners (input : Section199Input) : Currency :=
  let year := input.taxYear.year
  -- Check if (c)(3)(C) is applicable
  -- (ii) Termination: Clause (i) shall not apply to any taxable year beginning after December 31, 2021.
  let applicable_year := year <= 2021
  
  if applicable_year && 
     input.in_business_of_refining_crude_oil && 
     !input.is_major_integrated_oil_company then
    -- (i) ... amount allocated ... shall be 25 percent of the amount properly allocable ...
    let cost : Int := input.oil_transportation_costs_allocable
    (cost * 25) / 100
  else
    input.oil_transportation_costs_allocable

/-
Define a helper function to determine if the Puerto Rico provisions of Section 199(d)(8) apply, using explicit Int casting.
-/
def is_puerto_rico_applies (input : Section199Input) : Bool :=
  let year := input.taxYear.year
  -- (C) Termination: ... beginning after Dec 31, 2005, and before Jan 1, 2017.
  let time_window := year >= 2006 && year < 2017
  
  let receipts : Int := input.gross_receipts_from_puerto_rico
  
  time_window && 
  (receipts > 0) &&
  input.all_puerto_rico_receipts_taxable_us

/-
Define the calculation for total W-2 wages, adding Puerto Rico wages if the special rule applies.
-/
def total_w2_wages (input : Section199Input) : Currency :=
  if is_puerto_rico_applies input then
    -- (B) ... determination of W-2 wages ... shall be made without regard to any exclusion under section 3401(a)(8)
    -- This implies we add the Puerto Rico wages which might otherwise be excluded.
    let w2_excl : Int := input.w2_wages_excluding_puerto_rico
    let pr_wages : Int := input.puerto_rico_wages
    w2_excl + pr_wages
  else
    input.w2_wages_excluding_puerto_rico

/-
Theorem: If the conditions for Section 199(c)(3)(C) are met, the transportation costs are 25% of the allocable amount. Using let bindings to ensure Int arithmetic.
-/
theorem transportation_costs_independent_refiners_correct (input : Section199Input) :
  let year := input.taxYear.year
  let applicable_year := year <= 2021
  applicable_year ∧ input.in_business_of_refining_crude_oil ∧ ¬input.is_major_integrated_oil_company →
  let cost : Int := input.oil_transportation_costs_allocable
  let result : Int := transportation_costs_independent_refiners input
  result = (cost * 25) / 100 := by
  unfold transportation_costs_independent_refiners; aesop;

/-
Theorem: Verify the correctness of the total W-2 wages calculation under Section 199(d)(8), ensuring Puerto Rico wages are included if and only if the conditions are met.
-/
theorem total_w2_wages_correct (input : Section199Input) :
  let year := input.taxYear.year
  let time_window := year >= 2006 && year < 2017
  let receipts : Int := input.gross_receipts_from_puerto_rico
  let pr_applies := time_window && (receipts > 0) && input.all_puerto_rico_receipts_taxable_us

  let w2_excl : Int := input.w2_wages_excluding_puerto_rico
  let pr_wages : Int := input.puerto_rico_wages
  let result : Int := total_w2_wages input

  if pr_applies then
    result = w2_excl + pr_wages
  else
    result = w2_excl := by
  unfold total_w2_wages;
  unfold is_puerto_rico_applies; aesop;