/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: dd867586-9834-4d5f-9a10-657ef50ec68a
-/

/-
Formalization of IRC Section 274 (Disallowance of certain entertainment, etc., expenses).

This module defines the necessary data structures and functions to calculate deductible expenses under IRC §274, covering:
- §274(a): Disallowance of entertainment, amusement, recreation, and club dues.
- §274(b): Limitation on gifts ($25 limit per recipient per year), with exceptions for small imprinted items and promotional materials.
- §274(c): Limitations on foreign travel expenses, allocating costs between business and personal time unless exceptions apply (travel ≤ 1 week or personal time < 25%).
- §274(d): Substantiation requirements for travel, gifts, and listed property.

Key definitions include:
- `Expense` and `ExpenseCategory`: Representing different types of expenses.
- `TaxContext`: Holding context such as prior gifts for aggregation.
- `calculateDeductibleAmount`: The main function computing the deductible portion of an expense.

Theorems are provided to verify the correctness of the implementation against the legal text, such as `entertainment_disallowed`, `gift_limit_check`, and `foreign_travel_exception_applies`.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
Basic definitions for IRC Section 274 formalization including Currency, TaxYear, and FilingStatus.
-/
-- Common definitions
def Currency := Int

structure TaxYear where
  year : Nat
  h_valid : year ≥ 1913
  deriving DecidableEq

inductive FilingStatus
  | Single                         -- IRC §1(c)
  | MarriedFilingJointly          -- IRC §1(a)
  | MarriedFilingSeparately       -- IRC §1(d)
  | HeadOfHousehold               -- IRC §1(b)
  | QualifyingWidower             -- IRC §2(b)
  | Estate                         -- IRC §1(e)(1)
  | Trust                          -- IRC §1(e)(2)
  deriving Repr, DecidableEq, Inhabited

/-
Adding Repr instances for Currency and TaxYear.
-/
instance : Repr Currency := inferInstanceAs (Repr Int)

deriving instance Repr for TaxYear

/-
Definitions for ExpenseCategory and Expense structures to represent the different types of expenses mentioned in IRC §274.
-/
structure GiftDetails where
  recipient : String
  cost : Currency
  has_name_imprinted : Bool
  is_widely_distributed : Bool
  is_promotional_material : Bool
  deriving DecidableEq, Repr

inductive ExpenseCategory
  | EntertainmentActivity
  | EntertainmentFacility
  | ClubDues
  | QualifiedTransportationFringe
  | Gift (details : GiftDetails)
  | ForeignTravel (days : Nat) (business_days : Nat)
  | Other
  deriving DecidableEq, Repr

structure Expense where
  amount : Currency
  category : ExpenseCategory
  date : TaxYear
  description : String
  substantiated : Bool
  deriving DecidableEq, Repr

/-
Defining TaxContext to hold prior gifts, and a function to check if an expense is disallowed under IRC §274(a) (Entertainment, Club Dues, Qualified Transportation Fringes).
-/
structure TaxContext where
  priorGifts : List Expense
  deriving DecidableEq, Repr

-- IRC §274(a) Disallowance of certain entertainment, etc., expenses
def isSection274aDisallowed (e : Expense) : Bool :=
  match e.category with
  | ExpenseCategory.EntertainmentActivity => true
  | ExpenseCategory.EntertainmentFacility => true
  | ExpenseCategory.ClubDues => true
  | ExpenseCategory.QualifiedTransportationFringe => true
  | _ => false

/-
Adding typeclass instances for Currency to support arithmetic, comparisons, and numeric literals.
-/
instance : Add Currency := inferInstanceAs (Add Int)
instance : Sub Currency := inferInstanceAs (Sub Int)
instance : Mul Currency := inferInstanceAs (Mul Int)
instance : LE Currency := inferInstanceAs (LE Int)
instance : LT Currency := inferInstanceAs (LT Int)
instance : LinearOrder Currency := inferInstanceAs (LinearOrder Int)
instance {n} : OfNat Currency n := ⟨(n : Int)⟩

/-
Implementation of IRC §274(b) Gift limitations.
Defines constants for limits ($25 and $4).
Helper `isGiftException` checks for the exceptions (imprinted items < $4, promotional material).
`calculateDeductibleGiftAmount` calculates the deductible amount for a gift expense, considering prior gifts to the same recipient in the same year.
If an item is an exception, it is fully deductible (under this section).
Otherwise, it is limited to the remaining allowance ($25 - prior gifts).
-/
-- IRC §274(b) Gifts

def GiftLimit : Currency := 25
def GiftExceptionLimit : Currency := 4

def isGiftException (details : GiftDetails) : Bool :=
  (details.cost <= GiftExceptionLimit && details.has_name_imprinted && details.is_widely_distributed) ||
  details.is_promotional_material

def getGiftRecipient (e : Expense) : Option String :=
  match e.category with
  | ExpenseCategory.Gift details => some details.recipient
  | _ => none

def isSubjectToGiftLimitation (e : Expense) : Bool :=
  match e.category with
  | ExpenseCategory.Gift details => !isGiftException details
  | _ => false

def calculateDeductibleGiftAmount (ctx : TaxContext) (e : Expense) : Currency :=
  match e.category with
  | ExpenseCategory.Gift details =>
    if isGiftException details then
      e.amount
    else
      let recipient := details.recipient
      let year := e.date.year
      let priorAmount := ctx.priorGifts.foldl (fun sum prior =>
        if prior.date.year == year &&
           getGiftRecipient prior == some recipient &&
           isSubjectToGiftLimitation prior then
          sum + prior.amount
        else
          sum
      ) 0
      let remainingAllowance := max (0 : Currency) (GiftLimit - priorAmount)
      min e.amount remainingAllowance
  | _ => e.amount

/-
Implementation of IRC §274(c) Foreign Travel limitations.
Checks exceptions: travel <= 1 week, or personal time < 25%.
If exception applies, full amount is deductible.
Otherwise, allocates deduction based on the ratio of business days to total days.
Explicitly casts to Int to avoid type ambiguity.
-/
-- IRC §274(c) Certain foreign travel

def isForeignTravelException (totalDays : Nat) (businessDays : Nat) : Bool :=
  -- (A) such travel does not exceed one week
  totalDays <= 7 ||
  -- (B) personal time is less than 25 percent of the total time
  -- personalDays / totalDays < 1/4  <=>  4 * personalDays < totalDays
  let personalDays := totalDays - businessDays
  4 * personalDays < totalDays

def calculateDeductibleForeignTravel (e : Expense) : Currency :=
  match e.category with
  | ExpenseCategory.ForeignTravel totalDays businessDays =>
    if totalDays == 0 then 0 else
    if isForeignTravelException totalDays businessDays then
      e.amount
    else
      -- Allocate based on business days ratio
      -- amount * (businessDays / totalDays)
      -- We perform the multiplication first to avoid integer division truncation issues
      let amountInt : Int := e.amount
      let businessDaysInt : Int := businessDays
      let totalDaysInt : Int := totalDays
      (amountInt * businessDaysInt) / totalDaysInt
  | _ => e.amount

/-
Implementation of IRC §274(d) Substantiation requirements and the main `calculateDeductibleAmount` function.
`requiresSubstantiation` determines if a category falls under §274(d).
`isDeductionAllowed` checks §274(a) (general disallowance) and §274(d) (substantiation).
`calculateDeductibleAmount` applies the specific limitations (§274(b) for gifts, §274(c) for foreign travel) if the deduction is otherwise allowed.
-/
-- IRC §274(d) Substantiation required

def requiresSubstantiation (category : ExpenseCategory) : Bool :=
  match category with
  | ExpenseCategory.ForeignTravel _ _ => true
  | ExpenseCategory.Gift _ => true
  | ExpenseCategory.EntertainmentActivity => true -- Generally required if it were allowed
  | ExpenseCategory.EntertainmentFacility => true
  | ExpenseCategory.ClubDues => true
  | ExpenseCategory.QualifiedTransportationFringe => true -- Listed property often includes cars
  | ExpenseCategory.Other => false -- Assuming ordinary expenses don't trigger §274(d) specifically

def isDeductionAllowed (ctx : TaxContext) (e : Expense) : Bool :=
  -- Check §274(a) Disallowance
  if isSection274aDisallowed e then false
  -- Check §274(d) Substantiation
  else if requiresSubstantiation e.category && !e.substantiated then false
  else true

def calculateDeductibleAmount (ctx : TaxContext) (e : Expense) : Currency :=
  if !isDeductionAllowed ctx e then
    0
  else
    match e.category with
    | ExpenseCategory.Gift _ => calculateDeductibleGiftAmount ctx e
    | ExpenseCategory.ForeignTravel _ _ => calculateDeductibleForeignTravel e
    | _ => e.amount

/-
Theorem: Entertainment expenses are disallowed (deductible amount is 0).
-/
theorem entertainment_disallowed (ctx : TaxContext) (e : Expense) :
  e.category = ExpenseCategory.EntertainmentActivity →
  calculateDeductibleAmount ctx e = 0 := by
  intro h
  unfold calculateDeductibleAmount isDeductionAllowed isSection274aDisallowed
  rw [h]
  simp

/-
Theorem: Gifts are capped at $25 (assuming substantiated, no prior gifts, and not an exception).
-/
theorem gift_limit_check (ctx : TaxContext) (e : Expense) (details : GiftDetails) :
  e.category = ExpenseCategory.Gift details →
  e.substantiated = true →
  ¬ isGiftException details →
  ctx.priorGifts = [] →
  e.amount > 25 →
  calculateDeductibleAmount ctx e = 25 := by
    unfold calculateDeductibleAmount at * ; aesop;
    · unfold isDeductionAllowed at h; aesop;
      unfold isSection274aDisallowed at h; aesop;
    · unfold calculateDeductibleGiftAmount; aesop;
      exact min_eq_right a_4.le

/-
Theorem: Foreign travel expenses are fully deductible if the trip is 7 days or less (and substantiated, and duration > 0).
-/
theorem foreign_travel_exception_applies (ctx : TaxContext) (e : Expense) (days business : Nat) :
  e.category = ExpenseCategory.ForeignTravel days business →
  e.substantiated = true →
  days > 0 →
  days ≤ 7 →
  calculateDeductibleAmount ctx e = e.amount := by
  intro h_cat h_sub h_pos h_days
  unfold calculateDeductibleAmount isDeductionAllowed isSection274aDisallowed calculateDeductibleForeignTravel isForeignTravelException
  rw [h_cat]
  simp [h_sub]
  -- The condition days <= 7 makes isForeignTravelException true
  have h_exc : days ≤ 7 ∨ 4 * (days - business) < days := Or.inl h_days
  simp [h_exc]
  -- Handle the days = 0 check
  have h_nonzero : days ≠ 0 := Nat.ne_of_gt h_pos
  simp [h_nonzero]

/-
Theorem: Unsubstantiated expenses are disallowed (deductible amount is 0) if substantiation is required.
-/
theorem unsubstantiated_disallowed (ctx : TaxContext) (e : Expense) :
  requiresSubstantiation e.category →
  e.substantiated = false →
  calculateDeductibleAmount ctx e = 0 := by
  intro h_req h_not_sub
  unfold calculateDeductibleAmount isDeductionAllowed
  split
  · rfl
  · simp [h_req, h_not_sub]