/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 66332a0f-abdc-43d8-8834-35f944f28ac7
-/

/-
Formalization of IRC Section 61 (Gross Income Defined).
This module defines the structure of gross income, including compensation, business income,
property gains, and other sources listed in §61(a).
It implements the calculation of gross income, handling the specific rules for alimony
based on the execution date of the divorce instrument (pre/post Dec 31, 2018).
Includes types for Currency, TaxYear, FilingStatus, and helper structures for detailed compensation.
Theorems verify the correctness of the income aggregation and the conditional inclusion of alimony.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
Basic types for IRC Section 61 formalization: Currency, TaxYear, and FilingStatus.
-/
-- Common definitions (inline these if needed)
def Currency := Int

structure TaxYear where
  year : Nat
  h_valid : year ≥ 1913
  deriving DecidableEq

inductive FilingStatus
  | Single
  | MarriedFilingJointly
  | MarriedFilingSeparately
  | HeadOfHousehold
  | QualifyingWidower
  deriving DecidableEq, Repr

/-
Structure representing the sources of income listed in IRC §61(a), with Repr instance for Currency.
-/
instance : Repr Currency := inferInstanceAs (Repr Int)

structure IncomeSources where
  compensation : Currency -- (1) Compensation for services
  business_income : Currency -- (2) Gross income derived from business
  property_gains : Currency -- (3) Gains derived from dealings in property
  interest : Currency -- (4) Interest
  rents : Currency -- (5) Rents
  royalties : Currency -- (6) Royalties
  dividends : Currency -- (7) Dividends
  annuities : Currency -- (8) Annuities
  life_insurance_income : Currency -- (9) Income from life insurance and endowment contracts
  pensions : Currency -- (10) Pensions
  discharge_of_indebtedness : Currency -- (11) Income from discharge of indebtedness
  partnership_share : Currency -- (12) Distributive share of partnership gross income
  decedent_income : Currency -- (13) Income in respect of a decedent
  estate_trust_income : Currency -- (14) Income from an interest in an estate or trust
  other_income : Currency -- Catch-all for "all income from whatever source derived"
  deriving DecidableEq, Repr

/-
Instances for Currency and the calculateGrossIncome function.
-/
instance : Add Currency := inferInstanceAs (Add Int)
instance : Zero Currency := inferInstanceAs (Zero Int)

def calculateGrossIncome (sources : IncomeSources) : Currency :=
  sources.compensation +
  sources.business_income +
  sources.property_gains +
  sources.interest +
  sources.rents +
  sources.royalties +
  sources.dividends +
  sources.annuities +
  sources.life_insurance_income +
  sources.pensions +
  sources.discharge_of_indebtedness +
  sources.partnership_share +
  sources.decedent_income +
  sources.estate_trust_income +
  sources.other_income

/-
Instances for numeric literals and negation for Currency, followed by the theorem verifying gross income calculation and an example.
-/
instance (n : Nat) : OfNat Currency n := inferInstanceAs (OfNat Int n)
instance : Neg Currency := inferInstanceAs (Neg Int)

theorem gross_income_includes_all_sources (s : IncomeSources) :
  calculateGrossIncome s =
  s.compensation + s.business_income + s.property_gains + s.interest +
  s.rents + s.royalties + s.dividends + s.annuities + s.life_insurance_income +
  s.pensions + s.discharge_of_indebtedness + s.partnership_share +
  s.decedent_income + s.estate_trust_income + s.other_income := by
  rfl

-- Example usage
def exampleIncome : IncomeSources := {
  compensation := 50000
  business_income := 10000
  property_gains := 5000
  interest := 200
  rents := 0
  royalties := 0
  dividends := 100
  annuities := 0
  life_insurance_income := 0
  pensions := 0
  discharge_of_indebtedness := 0
  partnership_share := 0
  decedent_income := 0
  estate_trust_income := 0
  other_income := 0
}

#eval calculateGrossIncome exampleIncome

/-
Structure and calculation for detailed compensation components as mentioned in IRC §61(a)(1).
-/
structure CompensationDetails where
  fees : Currency
  commissions : Currency
  fringe_benefits : Currency
  similar_items : Currency
  deriving DecidableEq, Repr

def totalCompensation (details : CompensationDetails) : Currency :=
  details.fees + details.commissions + details.fringe_benefits + details.similar_items

theorem compensation_sum_correct (d : CompensationDetails) :
  totalCompensation d = d.fees + d.commissions + d.fringe_benefits + d.similar_items := by
  rfl

/-
Date structure and DivorceInstrument structure to handle the alimony effective date rules.
-/
structure Date where
  year : Nat
  month : Nat
  day : Nat
  deriving DecidableEq, Repr, Ord

def Date.le (d1 d2 : Date) : Bool :=
  if d1.year < d2.year then true
  else if d1.year > d2.year then false
  else if d1.month < d2.month then true
  else if d1.month > d2.month then false
  else d1.day <= d2.day

instance : LE Date where
  le d1 d2 := Date.le d1 d2

structure DivorceInstrument where
  executionDate : Date
  modificationDate : Option Date
  modificationAdoptsNewRules : Bool
  deriving DecidableEq, Repr

/-
Defining LT instance for Date, cutoffDate, isAlimonyTaxable logic, and the theorem about alimony taxability.
-/
def Date.lt (d1 d2 : Date) : Bool :=
  if d1.year < d2.year then true
  else if d1.year > d2.year then false
  else if d1.month < d2.month then true
  else if d1.month > d2.month then false
  else d1.day < d2.day

instance : LT Date where
  lt d1 d2 := Date.lt d1 d2

instance (d1 d2 : Date) : Decidable (d1 ≤ d2) :=
  if h : Date.le d1 d2 then isTrue h else isFalse h

instance (d1 d2 : Date) : Decidable (d1 < d2) :=
  if h : Date.lt d1 d2 then isTrue h else isFalse h

def cutoffDate : Date := { year := 2018, month := 12, day := 31 }

def isAlimonyTaxable (instrument : DivorceInstrument) : Bool :=
  let newRulesApply :=
    if instrument.executionDate > cutoffDate then
      true
    else
      match instrument.modificationDate with
      | some modDate => modDate > cutoffDate && instrument.modificationAdoptsNewRules
      | none => false
  !newRulesApply

theorem alimony_taxable_before_cutoff (d : DivorceInstrument) :
  d.executionDate <= cutoffDate → d.modificationDate = none → isAlimonyTaxable d = true := by
  intro h_exec h_mod
  unfold isAlimonyTaxable
  simp [h_mod]
  -- We need to show that if d.executionDate <= cutoffDate, then !(d.executionDate > cutoffDate)
  -- This requires relating LE and LT.
  -- Since we are just defining the logic, we can leave the proof as sorry.
  -- The cutoff date is January 1, 2019, and the execution date is some date before that. Therefore, the cutoff date is not less than the execution date.
  simp [cutoffDate];
  -- Since the cutoff date is December 31, 2018, and the execution date is before that, the execution date must be December 31, 2018.
  have h_exec_date : d.executionDate ≤ ⟨2018, 12, 31⟩ := by
    exact h_exec;
  unfold instLEDate at *; aesop;
  unfold instLTDate at *; aesop;
  unfold Date.lt at *; aesop;
  · unfold Date.le at h_exec_date; aesop;
    linarith;
  · unfold Date.le at * ; aesop;
    all_goals linarith;
  · unfold Date.le at h_exec_date; aesop;
    · linarith;
    · linarith;
    · linarith

/-
Function to calculate gross income including alimony if applicable, and a theorem verifying the conditional logic.
-/
def calculateGrossIncomeWithAlimony (sources : IncomeSources) (alimony : Currency) (instrument : DivorceInstrument) : Currency :=
  let baseIncome := calculateGrossIncome sources
  if isAlimonyTaxable instrument then
    baseIncome + alimony
  else
    baseIncome

theorem alimony_inclusion_logic (sources : IncomeSources) (alimony : Currency) (instrument : DivorceInstrument) :
  (isAlimonyTaxable instrument = true → calculateGrossIncomeWithAlimony sources alimony instrument = calculateGrossIncome sources + alimony) ∧
  (isAlimonyTaxable instrument = false → calculateGrossIncomeWithAlimony sources alimony instrument = calculateGrossIncome sources) := by
  constructor
  · intro h
    unfold calculateGrossIncomeWithAlimony
    rw [h]
    simp
  · intro h
    unfold calculateGrossIncomeWithAlimony
    rw [h]
    simp

/-
Adding Repr instance for TaxYear, defining TaxpayerProfile, finalGrossIncome, and proving correctness theorems.
-/
instance : Repr TaxYear where
  reprPrec t _ := repr t.year

structure TaxpayerProfile where
  taxYear : TaxYear
  filingStatus : FilingStatus
  incomeSources : IncomeSources
  alimonyReceived : Option (Currency × DivorceInstrument) -- Amount and the instrument
  deriving DecidableEq, Repr

def finalGrossIncome (profile : TaxpayerProfile) : Currency :=
  let base := calculateGrossIncome profile.incomeSources
  match profile.alimonyReceived with
  | some (amount, instrument) =>
    if isAlimonyTaxable instrument then base + amount else base
  | none => base

theorem final_income_includes_taxable_alimony (profile : TaxpayerProfile) (amount : Currency) (instr : DivorceInstrument) :
  profile.alimonyReceived = some (amount, instr) →
  isAlimonyTaxable instr = true →
  finalGrossIncome profile = calculateGrossIncome profile.incomeSources + amount := by
  intro h_alimony h_taxable
  unfold finalGrossIncome
  rw [h_alimony]
  simp [h_taxable]

theorem final_income_excludes_nontaxable_alimony (profile : TaxpayerProfile) (amount : Currency) (instr : DivorceInstrument) :
  profile.alimonyReceived = some (amount, instr) →
  isAlimonyTaxable instr = false →
  finalGrossIncome profile = calculateGrossIncome profile.incomeSources := by
  intro h_alimony h_nontaxable
  unfold finalGrossIncome
  rw [h_alimony]
  simp [h_nontaxable]

/-
Examples demonstrating the calculation of gross income for different scenarios: simple case, old alimony rules (taxable), and new alimony rules (non-taxable).
-/
-- Example 1: Simple case, no alimony
def profileSimple : TaxpayerProfile := {
  taxYear := { year := 2023, h_valid := by simp },
  filingStatus := FilingStatus.Single,
  incomeSources := {
    compensation := 60000,
    business_income := 0,
    property_gains := 0,
    interest := 100,
    rents := 0,
    royalties := 0,
    dividends := 50,
    annuities := 0,
    life_insurance_income := 0,
    pensions := 0,
    discharge_of_indebtedness := 0,
    partnership_share := 0,
    decedent_income := 0,
    estate_trust_income := 0,
    other_income := 0
  },
  alimonyReceived := none
}

#eval finalGrossIncome profileSimple

-- Example 2: Alimony from old instrument (taxable)
-- Instrument executed in 2015, no modification
def oldInstrument : DivorceInstrument := {
  executionDate := { year := 2015, month := 6, day := 15 },
  modificationDate := none,
  modificationAdoptsNewRules := false
}

def profileOldAlimony : TaxpayerProfile := {
  taxYear := { year := 2023, h_valid := by simp },
  filingStatus := FilingStatus.Single,
  incomeSources := {
    compensation := 40000,
    business_income := 0,
    property_gains := 0,
    interest := 0,
    rents := 0,
    royalties := 0,
    dividends := 0,
    annuities := 0,
    life_insurance_income := 0,
    pensions := 0,
    discharge_of_indebtedness := 0,
    partnership_share := 0,
    decedent_income := 0,
    estate_trust_income := 0,
    other_income := 0
  },
  alimonyReceived := some (12000, oldInstrument)
}

#eval finalGrossIncome profileOldAlimony

-- Example 3: Alimony from new instrument (not taxable)
-- Instrument executed in 2020
def newInstrument : DivorceInstrument := {
  executionDate := { year := 2020, month := 1, day := 1 },
  modificationDate := none,
  modificationAdoptsNewRules := false
}

def profileNewAlimony : TaxpayerProfile := {
  taxYear := { year := 2023, h_valid := by simp },
  filingStatus := FilingStatus.Single,
  incomeSources := {
    compensation := 40000,
    business_income := 0,
    property_gains := 0,
    interest := 0,
    rents := 0,
    royalties := 0,
    dividends := 0,
    annuities := 0,
    life_insurance_income := 0,
    pensions := 0,
    discharge_of_indebtedness := 0,
    partnership_share := 0,
    decedent_income := 0,
    estate_trust_income := 0,
    other_income := 0
  },
  alimonyReceived := some (12000, newInstrument)
}

#eval finalGrossIncome profileNewAlimony