/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 656224d3-4d8b-46a3-a1c1-97b877b5c86d
-/

/-
Formalization of IRC Section 1011: Adjusted basis for determining gain or loss.
This module defines the structures and functions necessary to calculate the adjusted basis
under the general rule (Section 1011(a)) and the special rule for bargain sales to charitable organizations (Section 1011(b)).
It includes theorems verifying the correctness of the logic, such as the adjusted basis being the general adjusted basis
when it is not a charitable bargain sale, and handling edge cases like zero fair market value.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

-- Common definitions (inline these if needed)
def Currency := Int
structure TaxYear where
  year : Nat
  h_valid : year ≥ 1913
  deriving DecidableEq

inductive FilingStatus
  | Single                         -- IRC §1(c)
  | MarriedFilingJointly          -- IRC §1(a)
  | MarriedFilingSeparately       -- IRC §1(d)
  | HeadOfHousehold               -- IRC §1(b)
  | QualifyingWidower             -- IRC §2(b)
  | Estate                         -- IRC §1(e)(1)
  | Trust                          -- IRC §1(e)(2)
  deriving Repr, DecidableEq, Inhabited

/-
Provide necessary typeclass instances for Currency since it was defined as a def (opaque alias) of Int.
-/
instance : Repr Currency := inferInstanceAs (Repr Int)
instance : Add Currency := inferInstanceAs (Add Int)
instance : Sub Currency := inferInstanceAs (Sub Int)
instance : Mul Currency := inferInstanceAs (Mul Int)
instance : Div Currency := inferInstanceAs (Div Int)
instance : LE Currency := inferInstanceAs (LE Int)
instance : LT Currency := inferInstanceAs (LT Int)
instance : DecidableEq Currency := inferInstanceAs (DecidableEq Int)
instance : Inhabited Currency := inferInstanceAs (Inhabited Int)
instance (n : Nat) : OfNat Currency n := inferInstanceAs (OfNat Int n)

/-
Defines the structure for property disposition and implements the logic for IRC Section 1011(a) and 1011(b).
-/
structure PropertyDisposition where
  /-- The cost or other basis determined under section 1012 or other applicable sections. -/
  basis : Currency
  /-- Adjustments to basis as provided in section 1016. -/
  adjustments : Currency
  /-- The amount realized from the sale or disposition. -/
  amountRealized : Currency
  /-- The fair market value of the property. -/
  fairMarketValue : Currency
  /-- Whether a deduction is allowable under section 170 (charitable contributions) by reason of the sale. -/
  isCharitableBargainSale : Bool
  deriving Repr, DecidableEq

/--
IRC §1011(a) General rule
The adjusted basis for determining the gain or loss from the sale or other disposition of property,
whenever acquired, shall be the basis (determined under section 1012 or other applicable sections...),
adjusted as provided in section 1016.
-/
def adjustedBasisGeneral (prop : PropertyDisposition) : Currency :=
  prop.basis + prop.adjustments

/--
IRC §1011(b) Bargain sale to a charitable organization
If a deduction is allowable under section 170 (relating to charitable contributions) by reason of a sale,
then the adjusted basis for determining the gain from such sale shall be that portion of the adjusted basis
which bears the same ratio to the adjusted basis as the amount realized bears to the fair market value of the property.
-/
def adjustedBasisBargainSale (prop : PropertyDisposition) : Currency :=
  let generalAdjBasis := adjustedBasisGeneral prop
  if prop.fairMarketValue = 0 then
    0 -- Avoid division by zero; technically FMV shouldn't be 0 in a sale, but handle safely.
  else
    (prop.amountRealized * generalAdjBasis) / prop.fairMarketValue

/--
IRC §1011 Adjusted basis for determining gain or loss
Combines the general rule and the bargain sale rule.
-/
def adjustedBasis (prop : PropertyDisposition) : Currency :=
  if prop.isCharitableBargainSale then
    adjustedBasisBargainSale prop
  else
    adjustedBasisGeneral prop

/-
Theorem: If it is not a charitable bargain sale, the adjusted basis is the general adjusted basis.
-/
/--
Theorem: If it is not a charitable bargain sale, the adjusted basis is the general adjusted basis.
-/
theorem adjustedBasis_eq_general_of_not_charitable (prop : PropertyDisposition)
    (h : prop.isCharitableBargainSale = false) :
    adjustedBasis prop = adjustedBasisGeneral prop := by
  unfold adjustedBasis;
  aesop

/-
Theorem: In a charitable bargain sale, if the fair market value is zero, the adjusted basis is zero.
-/
/--
Theorem: In a charitable bargain sale, if the fair market value is zero, the adjusted basis is zero.
-/
theorem adjustedBasis_bargain_fmv_zero (prop : PropertyDisposition)
    (h_charitable : prop.isCharitableBargainSale = true)
    (h_fmv : prop.fairMarketValue = 0) :
    adjustedBasis prop = 0 := by
  unfold adjustedBasis;
  unfold adjustedBasisBargainSale; aesop

/-
Theorem: In a charitable bargain sale, if the amount realized equals the fair market value, then the adjusted basis equals the general adjusted basis.
-/
/--
Theorem: In a charitable bargain sale, if the amount realized equals the fair market value (and FMV is non-zero),
then the adjusted basis equals the general adjusted basis.
This reflects that if there is no "bargain" element (full value realized), the ratio is 1.
-/
theorem adjustedBasis_bargain_eq_general_of_full_realization (prop : PropertyDisposition)
    (h_charitable : prop.isCharitableBargainSale = true)
    (h_fmv_nz : prop.fairMarketValue ≠ 0)
    (h_realized : prop.amountRealized = prop.fairMarketValue) :
    adjustedBasis prop = adjustedBasisGeneral prop := by
  unfold adjustedBasis; aesop;
  unfold adjustedBasisBargainSale; aesop;
  rw [ Int.mul_ediv_cancel_left _ h_fmv_nz ]