/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: ba0167ee-37dd-4022-b22b-58754d575893
-/

/-
Formalization of IRC Section 41 (Credit for Increasing Research Activities).
This module defines the necessary types (Currency, TaxYear, FilingStatus) and implements the calculation logic for the research credit, including qualified research expenses (in-house and contract) and the final credit amount.
It also includes theorems verifying key properties of the credit, such as non-negativity and the behavior when the base amount exceeds expenses.
An example calculation is provided and verified.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
Basic type definitions for IRC Section 41 formalization including Currency, TaxYear, and FilingStatus.
-/
/-- Currency amount in cents or smallest unit to avoid floating point issues. -/
def Currency := Int

/-- Represents a tax year, valid from 1913 onwards (inception of modern US income tax). -/
structure TaxYear where
  year : Nat
  h_valid : year ≥ 1913
  deriving DecidableEq

/-- Federal tax filing statuses. -/
inductive FilingStatus
  | Single
  | MarriedFilingJointly
  | MarriedFilingSeparately
  | HeadOfHousehold
  | QualifyingWidower
  deriving DecidableEq, Repr

/-
Explicitly providing typeclass instances for Currency to ensure it behaves exactly like Int for arithmetic, comparison, and representation.
-/
-- We need to ensure Currency behaves like Int for the structure deriving and calculations
instance : Repr Currency := inferInstanceAs (Repr Int)
instance : Add Currency := inferInstanceAs (Add Int)
instance : Sub Currency := inferInstanceAs (Sub Int)
instance : Mul Currency := inferInstanceAs (Mul Int)
instance : Div Currency := inferInstanceAs (Div Int)
instance : LT Currency := inferInstanceAs (LT Int)
instance : LE Currency := inferInstanceAs (LE Int)
instance : DecidableEq Currency := inferInstanceAs (DecidableEq Int)
instance : Inhabited Currency := inferInstanceAs (Inhabited Int)
instance (n : Nat) : OfNat Currency n := ⟨(n : Int)⟩
instance : LinearOrder Currency := inferInstanceAs (LinearOrder Int)

/-
Defines the input structure and calculation functions for IRC Section 41 research credit, using the Currency type and its instances.
-/
/-- Inputs required for calculating the research credit under IRC Section 41. -/
structure Section41Inputs where
  /-- Wages paid or incurred to an employee for qualified services. IRC §41(b)(2)(A)(i). -/
  wages_qualified_services : Currency
  /-- Amount paid or incurred for supplies used in the conduct of qualified research. IRC §41(b)(2)(A)(ii). -/
  supplies_qualified_research : Currency
  /-- Amount paid or incurred for the right to use computers in the conduct of qualified research. IRC §41(b)(2)(A)(iii). -/
  computer_rental_qualified_research : Currency
  /-- Amounts paid or incurred to any person (other than an employee) for qualified research. IRC §41(b)(3)(A). -/
  contract_research_amounts_general : Currency
  /-- Amounts paid to a qualified research consortium. IRC §41(b)(3)(C). -/
  contract_research_amounts_consortia : Currency
  /-- The base amount defined in IRC §41(c). -/
  base_amount : Currency
  /-- Basic research payments determined under subsection (e)(1)(A). IRC §41(a)(2). -/
  basic_research_payments : Currency
  /-- Amounts paid to an energy research consortium. IRC §41(a)(3). -/
  energy_research_consortium_payments : Currency
  deriving DecidableEq, Repr

/-- Helper to calculate a percentage of a currency amount. -/
def percent (amount : Currency) (p : Currency) : Currency :=
  (amount * p) / 100

/-- Calculates In-house research expenses. IRC §41(b)(2). -/
def calc_in_house_research_expenses (inputs : Section41Inputs) : Currency :=
  inputs.wages_qualified_services +
  inputs.supplies_qualified_research +
  inputs.computer_rental_qualified_research

/-- Calculates Contract research expenses. IRC §41(b)(3). -/
def calc_contract_research_expenses (inputs : Section41Inputs) : Currency :=
  let general := percent inputs.contract_research_amounts_general 65
  let consortia := percent inputs.contract_research_amounts_consortia 75
  general + consortia

/-- Calculates Qualified research expenses. IRC §41(b)(1). -/
def calc_qualified_research_expenses (inputs : Section41Inputs) : Currency :=
  calc_in_house_research_expenses inputs +
  calc_contract_research_expenses inputs

/-- Calculates the research credit. IRC §41(a). -/
def calc_research_credit (inputs : Section41Inputs) : Currency :=
  let qre := calc_qualified_research_expenses inputs
  let excess_qre := max 0 (qre - inputs.base_amount)
  let credit_qre := percent excess_qre 20
  let credit_basic := percent inputs.basic_research_payments 20
  let credit_energy := percent inputs.energy_research_consortium_payments 20
  credit_qre + credit_basic + credit_energy

/-
Theorem stating that the research credit is non-negative given non-negative inputs.
-/
/-- Theorem: The research credit is always non-negative if the inputs are non-negative. -/
theorem research_credit_nonneg (inputs : Section41Inputs)
  (h_wages : inputs.wages_qualified_services ≥ 0)
  (h_supplies : inputs.supplies_qualified_research ≥ 0)
  (h_computer : inputs.computer_rental_qualified_research ≥ 0)
  (h_contract_gen : inputs.contract_research_amounts_general ≥ 0)
  (h_contract_cons : inputs.contract_research_amounts_consortia ≥ 0)
  (h_basic : inputs.basic_research_payments ≥ 0)
  (h_energy : inputs.energy_research_consortium_payments ≥ 0) :
  calc_research_credit inputs ≥ 0 := by
  exact add_nonneg ( add_nonneg ( Int.ediv_nonneg ( mul_nonneg ( le_max_left _ _ ) ( by norm_num ) ) ( by norm_num ) ) ( Int.ediv_nonneg ( mul_nonneg h_basic ( by norm_num ) ) ( by norm_num ) ) ) ( Int.ediv_nonneg ( mul_nonneg h_energy ( by norm_num ) ) ( by norm_num ) )

/-
Theorem stating that the credit from QRE is zero if the base amount exceeds the qualified research expenses.
-/
/-- Theorem: If the base amount is greater than or equal to the qualified research expenses,
    the credit component from qualified research expenses is zero. -/
theorem credit_qre_zero_if_base_exceeds (inputs : Section41Inputs)
  (h_exceeds : inputs.base_amount ≥ calc_qualified_research_expenses inputs) :
  let qre := calc_qualified_research_expenses inputs
  let excess_qre := max 0 (qre - inputs.base_amount)
  percent excess_qre 20 = 0 := by
  -- Since the base amount exceeds the qualified research expenses, the excess is zero.
  have h_excess_zero : (calc_qualified_research_expenses inputs) - inputs.base_amount ≤ 0 := by
    exact Int.sub_nonpos_of_le h_exceeds;
  unfold percent; aesop;

/-
Theorem stating that qualified research expenses are the sum of in-house and contract research expenses.
-/
/-- Theorem: Qualified research expenses are the sum of in-house and contract research expenses. -/
theorem qre_eq_in_house_plus_contract (inputs : Section41Inputs) :
  calc_qualified_research_expenses inputs =
  calc_in_house_research_expenses inputs + calc_contract_research_expenses inputs := by
  rfl

/-
Defines example inputs and a theorem verifying the research credit calculation for these inputs.
-/
/-- Example inputs for a hypothetical taxpayer. -/
def example_inputs : Section41Inputs := {
  wages_qualified_services := 100000
  supplies_qualified_research := 20000
  computer_rental_qualified_research := 5000
  contract_research_amounts_general := 10000
  contract_research_amounts_consortia := 0
  base_amount := 50000
  basic_research_payments := 0
  energy_research_consortium_payments := 0
}

/--
Test theorem verifying the calculation for the example inputs.
In-house: 100,000 + 20,000 + 5,000 = 125,000
Contract: 65% of 10,000 = 6,500
QRE: 125,000 + 6,500 = 131,500
Excess QRE: 131,500 - 50,000 = 81,500
Credit (20%): 16,300
-/
theorem example_calculation_correct : calc_research_credit example_inputs = 16300 := by
  rfl