/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 1f3f2b13-4423-4ffe-9b71-35e2058dbc77
-/

/-
Formalization of IRC Section 1014 regarding the basis of property acquired from a decedent.
This module defines the necessary types and structures to represent tax years, filing statuses, dates, and property details.
It implements the `calculateBasis` function which computes the basis according to the rules in §1014(a) and (b),
including handling of elections under §2032 and §2032A, the exclusion under §2031(c), and special rules for
Foreign Personal Holding Companies and property included in the gross estate under §1014(b)(9).
Theorems are provided to verify the correctness of the logic for various scenarios.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
Basic definitions for IRC Section 1014 formalization including Currency, TaxYear, and FilingStatus.
-/
/-- Currency amount in cents -/
def Currency := Int

/-- Tax year structure -/
structure TaxYear where
  year : Nat
  h_valid : year ≥ 1913
  deriving DecidableEq

/-- Filing status for tax purposes -/
inductive FilingStatus
  | Single
  | MarriedFilingJointly
  | MarriedFilingSeparately
  | HeadOfHousehold
  | QualifyingWidower
  deriving DecidableEq, Repr

/-
Define a Date structure to represent dates.
-/
/-- Simple Date structure -/
structure Date where
  year : Nat
  month : Nat
  day : Nat
  h_month : month ≥ 1 ∧ month ≤ 12
  h_day : day ≥ 1 ∧ day ≤ 31 -- Simplified
  deriving DecidableEq, Repr

/-
Implement Date comparison using a toNat conversion.
-/
/-- Convert Date to a natural number YYYYMMDD for easy comparison -/
def Date.toNat (d : Date) : Nat := d.year * 10000 + d.month * 100 + d.day

instance : LE Date := ⟨fun a b => a.toNat ≤ b.toNat⟩
instance : LT Date := ⟨fun a b => a.toNat < b.toNat⟩

instance (a b : Date) : Decidable (a ≤ b) := inferInstanceAs (Decidable (a.toNat ≤ b.toNat))
instance (a b : Date) : Decidable (a < b) := inferInstanceAs (Decidable (a.toNat < b.toNat))

/-
Provide Repr instance for Currency and define election structures.
-/
instance : Repr Currency := inferInstanceAs (Repr Int)

/-- Election under Section 2032 (Alternate Valuation) -/
structure Section2032Election where
  elected : Bool
  value : Currency -- Value at applicable valuation date
  deriving DecidableEq, Repr

/-- Election under Section 2032A (Special Use Valuation) -/
structure Section2032AElection where
  elected : Bool
  value : Currency -- Value determined under such section
  deriving DecidableEq, Repr

/-- Exclusion under Section 2031(c) (Conservation Easement) -/
structure Section2031cExclusion where
  applicable : Bool
  decedentBasis : Currency -- Basis in the hands of the decedent
  deriving DecidableEq, Repr

/-
Define AcquisitionMethod and PropertyDetails structures to capture the necessary information for basis calculation.
-/
/-- Methods of acquiring property from a decedent under §1014(b) -/
inductive AcquisitionMethod
  | BequestDeviseInheritance -- §1014(b)(1)
  | RevocableTrust -- §1014(b)(2)
  | TrustPowerToAlter -- §1014(b)(3)
  | GeneralPowerOfAppointment -- §1014(b)(4)
  | ForeignPersonalHoldingCompany -- §1014(b)(5)
  | CommunityProperty -- §1014(b)(6)
  | IncludedInGrossEstate -- §1014(b)(9)
  | QTIP -- §1014(b)(10)
  | Other -- Fallback
  deriving DecidableEq, Repr

/-- Details of the property and its acquisition -/
structure PropertyDetails where
  acquisitionMethod : AcquisitionMethod
  acquisitionDate : Date
  decedentDeathDate : Date
  dispositionDate : Option Date -- None if not disposed
  fairMarketValueAtDeath : Currency
  decedentBasis : Currency
  section2032 : Section2032Election
  section2032A : Section2032AElection
  section2031c : Section2031cExclusion
  deductionsAllowed : Currency -- For §1014(b)(9) reduction
  deriving DecidableEq, Repr

/-
Add necessary instances for Currency (Int) to support arithmetic and comparison.
-/
instance : LE Currency := inferInstanceAs (LE Int)
instance : LT Currency := inferInstanceAs (LT Int)
instance : Add Currency := inferInstanceAs (Add Int)
instance : Sub Currency := inferInstanceAs (Sub Int)
instance (n : Nat) : OfNat Currency n := inferInstanceAs (OfNat Int n)
instance : Inhabited Currency := inferInstanceAs (Inhabited Int)
instance : DecidableRel (· ≤ · : Currency → Currency → Prop) := inferInstanceAs (DecidableRel (· ≤ · : Int → Int → Prop))
instance : DecidableRel (· < · : Currency → Currency → Prop) := inferInstanceAs (DecidableRel (· < · : Int → Int → Prop))

/-
Implement the calculateBasis function according to IRC §1014 logic, handling dispositions, special rules for foreign personal holding companies, elections, and deductions.
-/
/-- Helper to convert Date to Nat for comparison with literals -/
def Date.toNatLiteral (y m d : Nat) : Nat := y * 10000 + m * 100 + d

/-- Calculate the basis of property acquired from a decedent under IRC §1014 -/
def calculateBasis (details : PropertyDetails) : Option Currency :=
  -- Check if disposed of before death (§1014(a))
  let disposedBeforeDeath :=
    match details.dispositionDate with
    | some d => d < details.decedentDeathDate
    | none => false

  if disposedBeforeDeath then
    none
  else
    -- Determine the unadjusted basis based on §1014(a) and (b)(5)
    let unadjustedBasis :=
      -- §1014(b)(5): Foreign Personal Holding Company
      if details.acquisitionMethod = AcquisitionMethod.ForeignPersonalHoldingCompany ∧
         details.decedentDeathDate.toNat > 19370826 ∧
         details.decedentDeathDate.toNat < 20050101 then
        if details.fairMarketValueAtDeath ≤ details.decedentBasis then
          details.fairMarketValueAtDeath
        else
          details.decedentBasis
      else
        -- §1014(a) General Rules
        if details.section2032.elected then
          details.section2032.value -- §1014(a)(2)
        else if details.section2032A.elected then
          details.section2032A.value -- §1014(a)(3)
        else if details.section2031c.applicable then
          details.section2031c.decedentBasis -- §1014(a)(4)
        else
          details.fairMarketValueAtDeath -- §1014(a)(1)

    -- Apply adjustments
    -- §1014(b)(9): Reduction for depreciation if acquired before death
    if details.acquisitionMethod = AcquisitionMethod.IncludedInGrossEstate ∧
       details.decedentDeathDate.toNat > 19531231 ∧
       details.acquisitionDate < details.decedentDeathDate then
      some (unadjustedBasis - details.deductionsAllowed)
    else
      some unadjustedBasis

/-
Theorem: If property is disposed of before the decedent's death, the basis is not determined under this section (returns none).
-/
/-- Theorem: If property is disposed of before the decedent's death, the basis is not determined under this section (returns none). -/
theorem basis_none_if_disposed_before_death (details : PropertyDetails)
  (h_disposed : details.dispositionDate.isSome)
  (h_before : details.dispositionDate.get h_disposed < details.decedentDeathDate) :
  calculateBasis details = none := by
  cases details ; aesop;
  unfold calculateBasis; aesop;
  · contradiction;
  · contradiction

/-
Theorem: If Section 2032 is elected, the basis is the value at the applicable valuation date (assuming no other overriding conditions).
-/
/-- Theorem: If Section 2032 is elected, the basis is the value at the applicable valuation date (assuming no other overriding conditions). -/
theorem basis_section2032_elected (details : PropertyDetails)
  (h_not_disposed : details.dispositionDate = none)
  (h_not_fphc : details.acquisitionMethod ≠ AcquisitionMethod.ForeignPersonalHoldingCompany)
  (h_no_adj : ¬(details.acquisitionMethod = AcquisitionMethod.IncludedInGrossEstate ∧
                details.decedentDeathDate.toNat > 19531231 ∧
                details.acquisitionDate < details.decedentDeathDate))
  (h_2032 : details.section2032.elected) :
  calculateBasis details = some details.section2032.value := by
  unfold calculateBasis; aesop;

/-
Theorem: If Section 2032A is elected and 2032 is not, the basis is the value determined under Section 2032A.
-/
/-- Theorem: If Section 2032A is elected and 2032 is not, the basis is the value determined under Section 2032A. -/
theorem basis_section2032A_elected (details : PropertyDetails)
  (h_not_disposed : details.dispositionDate = none)
  (h_not_fphc : details.acquisitionMethod ≠ AcquisitionMethod.ForeignPersonalHoldingCompany)
  (h_not_2032 : ¬details.section2032.elected)
  (h_no_adj : ¬(details.acquisitionMethod = AcquisitionMethod.IncludedInGrossEstate ∧
                details.decedentDeathDate.toNat > 19531231 ∧
                details.acquisitionDate < details.decedentDeathDate))
  (h_2032A : details.section2032A.elected) :
  calculateBasis details = some details.section2032A.value := by
  simp_all +decide [ calculateBasis ]

/-
Theorem: Default basis is Fair Market Value at death if no elections or special rules apply.
-/
/-- Theorem: Default basis is Fair Market Value at death if no elections or special rules apply. -/
theorem basis_default_fmv (details : PropertyDetails)
  (h_not_disposed : details.dispositionDate = none)
  (h_not_fphc : details.acquisitionMethod ≠ AcquisitionMethod.ForeignPersonalHoldingCompany)
  (h_not_2032 : ¬details.section2032.elected)
  (h_not_2032A : ¬details.section2032A.elected)
  (h_not_2031c : ¬details.section2031c.applicable)
  (h_no_adj : ¬(details.acquisitionMethod = AcquisitionMethod.IncludedInGrossEstate ∧
                details.decedentDeathDate.toNat > 19531231 ∧
                details.acquisitionDate < details.decedentDeathDate)) :
  calculateBasis details = some details.fairMarketValueAtDeath := by
  unfold calculateBasis; aesop;

/-
Define example PropertyDetails for testing.
-/
/-- Example 1: Simple bequest, no elections -/
def example1_details : PropertyDetails := {
  acquisitionMethod := AcquisitionMethod.BequestDeviseInheritance,
  acquisitionDate := { year := 2020, month := 1, day := 1, h_month := by decide, h_day := by decide },
  decedentDeathDate := { year := 2023, month := 5, day := 15, h_month := by decide, h_day := by decide },
  dispositionDate := none,
  fairMarketValueAtDeath := 100000, -- $1,000.00
  decedentBasis := 50000,
  section2032 := { elected := false, value := 0 },
  section2032A := { elected := false, value := 0 },
  section2031c := { applicable := false, decedentBasis := 0 },
  deductionsAllowed := 0
}

/-- Example 2: Disposed before death -/
def example2_details : PropertyDetails := {
  acquisitionMethod := AcquisitionMethod.BequestDeviseInheritance,
  acquisitionDate := { year := 2020, month := 1, day := 1, h_month := by decide, h_day := by decide },
  decedentDeathDate := { year := 2023, month := 5, day := 15, h_month := by decide, h_day := by decide },
  dispositionDate := some { year := 2022, month := 1, day := 1, h_month := by decide, h_day := by decide },
  fairMarketValueAtDeath := 100000,
  decedentBasis := 50000,
  section2032 := { elected := false, value := 0 },
  section2032A := { elected := false, value := 0 },
  section2031c := { applicable := false, decedentBasis := 0 },
  deductionsAllowed := 0
}

/-- Example 3: Section 2032 Election -/
def example3_details : PropertyDetails := {
  acquisitionMethod := AcquisitionMethod.BequestDeviseInheritance,
  acquisitionDate := { year := 2020, month := 1, day := 1, h_month := by decide, h_day := by decide },
  decedentDeathDate := { year := 2023, month := 5, day := 15, h_month := by decide, h_day := by decide },
  dispositionDate := none,
  fairMarketValueAtDeath := 100000,
  decedentBasis := 50000,
  section2032 := { elected := true, value := 95000 },
  section2032A := { elected := false, value := 0 },
  section2031c := { applicable := false, decedentBasis := 0 },
  deductionsAllowed := 0
}

/-
Verify the examples using theorems instead of #eval.
-/
/-- Verification of Example 1: Simple bequest, no elections -/
theorem example1_correct : calculateBasis example1_details = some 100000 := by
  unfold example1_details calculateBasis;
  grind

/-- Verification of Example 2: Disposed before death -/
theorem example2_correct : calculateBasis example2_details = none := by
  -- Apply the theorem that states if the property is disposed of before the decedent's death, the basis is not determined under this section.
  apply basis_none_if_disposed_before_death;
  all_goals norm_cast;
  norm_num [ example2_details ];
  exact Nat.succ_le_of_lt ( by decide )

/-- Verification of Example 3: Section 2032 Election -/
theorem example3_correct : calculateBasis example3_details = some 95000 := by
  unfold example3_details; simp +decide [ calculateBasis ] ;