/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 32975a3d-f6fa-4ae9-b29a-69afecfb80d2
-/

/-
Formalization of IRC Section 38 (General Business Credit).

This module defines the data structures and calculation functions for the General Business Credit
as specified in 26 U.S. Code § 38. It includes:
- Basic types for Currency, TaxYear, and FilingStatus.
- A structure `CurrentYearBusinessCreditComponents` representing the 40 individual credits listed in §38(b).
- A function `calc_current_year_business_credit` to sum these components.
- A structure `GeneralBusinessCreditInputs` representing the inputs for §38(a) (carryforwards, current year, carrybacks).
- A function `calc_general_business_credit` to calculate the total credit allowed.
- Theorems verifying the structural correctness of the calculations and an example evaluation.

-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
Define Currency, TaxYear, and FilingStatus types.
-/
/-- Currency amount in cents or smallest unit, represented as an integer. -/
def Currency := Int

/-- A tax year, which must be 1913 or later (inception of modern US income tax). -/
structure TaxYear where
  year : Nat
  h_valid : year ≥ 1913
  deriving DecidableEq

/-- Filing status for a taxpayer. -/
inductive FilingStatus
  | Single
  | MarriedFilingJointly
  | MarriedFilingSeparately
  | HeadOfHousehold
  | QualifyingWidower
  deriving DecidableEq, Repr

/-
Define instances for Currency.
-/
instance : Add Currency := inferInstanceAs (Add Int)
instance : Repr Currency := inferInstanceAs (Repr Int)
instance : DecidableEq Currency := inferInstanceAs (DecidableEq Int)
instance {n} : OfNat Currency n := inferInstanceAs (OfNat Int n)
instance : Inhabited Currency := inferInstanceAs (Inhabited Int)

/-
Define CurrentYearBusinessCreditComponents structure and calc_current_year_business_credit function.
-/
/-- Components of the current year business credit as defined in IRC §38(b). -/
structure CurrentYearBusinessCreditComponents where
  investment_credit : Currency -- (1) §46
  work_opportunity_credit : Currency -- (2) §51(a)
  alcohol_fuels_credit : Currency -- (3) §40(a)
  research_credit : Currency -- (4) §41(a)
  low_income_housing_credit : Currency -- (5) §42(a)
  enhanced_oil_recovery_credit : Currency -- (6) §43(a)
  disabled_access_credit : Currency -- (7) §44(a)
  renewable_electricity_production_credit : Currency -- (8) §45(a)
  empowerment_zone_employment_credit : Currency -- (9) §1396(a)
  indian_employment_credit : Currency -- (10) §45A(a)
  employer_social_security_credit : Currency -- (11) §45B(a)
  orphan_drug_credit : Currency -- (12) §45C(a)
  new_markets_tax_credit : Currency -- (13) §45D(a)
  small_employer_pension_plan_startup_cost_credit : Currency -- (14) §45E(a)
  employer_provided_child_care_credit : Currency -- (15) §45F(a)
  railroad_track_maintenance_credit : Currency -- (16) §45G(a)
  biodiesel_fuels_credit : Currency -- (17) §40A(a)
  low_sulfur_diesel_fuel_production_credit : Currency -- (18) §45H(a)
  marginal_oil_and_gas_well_production_credit : Currency -- (19) §45I(a)
  distilled_spirits_credit : Currency -- (20) §5011(a)
  advanced_nuclear_power_facility_production_credit : Currency -- (21) §45J(a)
  nonconventional_source_production_credit : Currency -- (22) §45K(a)
  new_energy_efficient_home_credit : Currency -- (23) §45L(a)
  alternative_motor_vehicle_credit : Currency -- (24) §30B(g)(1)
  alternative_fuel_vehicle_refueling_property_credit : Currency -- (25) §30C(d)(1)
  mine_rescue_team_training_credit : Currency -- (26) §45N(a)
  agricultural_chemicals_security_credit : Currency -- (27) §45O(a)
  differential_wage_payment_credit : Currency -- (28) §45P(a)
  carbon_dioxide_sequestration_credit : Currency -- (29) §45Q(a)
  new_clean_vehicle_credit : Currency -- (30) §30D(c)(1)
  small_employer_health_insurance_credit : Currency -- (31) §45R
  paid_family_and_medical_leave_credit : Currency -- (32) §45S(a)
  retirement_auto_enrollment_credit : Currency -- (33) §45T(a)
  zero_emission_nuclear_power_production_credit : Currency -- (34) §45U(a)
  sustainable_aviation_fuel_credit : Currency -- (35) §40B
  clean_hydrogen_production_credit : Currency -- (36) §45V(a)
  qualified_commercial_clean_vehicle_credit : Currency -- (37) §45W
  advanced_manufacturing_production_credit : Currency -- (38) §45X(a)
  clean_electricity_production_credit : Currency -- (39) §45Y(a)
  clean_fuel_production_credit : Currency -- (40) §45Z(a)
  deriving DecidableEq, Repr

/-- 
  Calculates the amount of the current year business credit.
  IRC §38(b): For purposes of this subpart, the amount of the current year business credit 
  is the sum of the following credits determined for the taxable year...
-/
def calc_current_year_business_credit (c : CurrentYearBusinessCreditComponents) : Currency :=
  c.investment_credit +
  c.work_opportunity_credit +
  c.alcohol_fuels_credit +
  c.research_credit +
  c.low_income_housing_credit +
  c.enhanced_oil_recovery_credit +
  c.disabled_access_credit +
  c.renewable_electricity_production_credit +
  c.empowerment_zone_employment_credit +
  c.indian_employment_credit +
  c.employer_social_security_credit +
  c.orphan_drug_credit +
  c.new_markets_tax_credit +
  c.small_employer_pension_plan_startup_cost_credit +
  c.employer_provided_child_care_credit +
  c.railroad_track_maintenance_credit +
  c.biodiesel_fuels_credit +
  c.low_sulfur_diesel_fuel_production_credit +
  c.marginal_oil_and_gas_well_production_credit +
  c.distilled_spirits_credit +
  c.advanced_nuclear_power_facility_production_credit +
  c.nonconventional_source_production_credit +
  c.new_energy_efficient_home_credit +
  c.alternative_motor_vehicle_credit +
  c.alternative_fuel_vehicle_refueling_property_credit +
  c.mine_rescue_team_training_credit +
  c.agricultural_chemicals_security_credit +
  c.differential_wage_payment_credit +
  c.carbon_dioxide_sequestration_credit +
  c.new_clean_vehicle_credit +
  c.small_employer_health_insurance_credit +
  c.paid_family_and_medical_leave_credit +
  c.retirement_auto_enrollment_credit +
  c.zero_emission_nuclear_power_production_credit +
  c.sustainable_aviation_fuel_credit +
  c.clean_hydrogen_production_credit +
  c.qualified_commercial_clean_vehicle_credit +
  c.advanced_manufacturing_production_credit +
  c.clean_electricity_production_credit +
  c.clean_fuel_production_credit

/-
Define GeneralBusinessCreditInputs structure and calc_general_business_credit function.
-/
/-- Inputs for calculating the general business credit under IRC §38(a). -/
structure GeneralBusinessCreditInputs where
  carryforwards : Currency -- (1) business credit carryforwards
  current_year_components : CurrentYearBusinessCreditComponents -- (2) current year business credit components
  carrybacks : Currency -- (3) business credit carrybacks
  deriving DecidableEq, Repr

/--
  Calculates the general business credit allowed for the taxable year.
  IRC §38(a): There shall be allowed as a credit against the tax imposed by this chapter 
  for the taxable year an amount equal to the sum of—
  (1) the business credit carryforwards carried to such taxable year,
  (2) the amount of the current year business credit, plus
  (3) the business credit carrybacks carried to such taxable year.
-/
def calc_general_business_credit (inputs : GeneralBusinessCreditInputs) : Currency :=
  inputs.carryforwards +
  calc_current_year_business_credit inputs.current_year_components +
  inputs.carrybacks

/-
Theorem: General business credit is sum of components.
-/
/--
  Theorem: The general business credit is the sum of carryforwards, current year credit, and carrybacks.
  This formally verifies the structure of IRC §38(a).
-/
theorem general_business_credit_eq_sum (inputs : GeneralBusinessCreditInputs) :
  calc_general_business_credit inputs = 
  inputs.carryforwards + 
  calc_current_year_business_credit inputs.current_year_components + 
  inputs.carrybacks := by
  rfl

/-
Define example inputs and prove the calculation is correct.
-/
/-- Example inputs for the general business credit calculation. -/
def example_inputs : GeneralBusinessCreditInputs := {
  carryforwards := 1000,
  current_year_components := {
    investment_credit := 500,
    work_opportunity_credit := 200,
    alcohol_fuels_credit := 0,
    research_credit := 300,
    low_income_housing_credit := 0,
    enhanced_oil_recovery_credit := 0,
    disabled_access_credit := 0,
    renewable_electricity_production_credit := 0,
    empowerment_zone_employment_credit := 0,
    indian_employment_credit := 0,
    employer_social_security_credit := 0,
    orphan_drug_credit := 0,
    new_markets_tax_credit := 0,
    small_employer_pension_plan_startup_cost_credit := 0,
    employer_provided_child_care_credit := 0,
    railroad_track_maintenance_credit := 0,
    biodiesel_fuels_credit := 0,
    low_sulfur_diesel_fuel_production_credit := 0,
    marginal_oil_and_gas_well_production_credit := 0,
    distilled_spirits_credit := 0,
    advanced_nuclear_power_facility_production_credit := 0,
    nonconventional_source_production_credit := 0,
    new_energy_efficient_home_credit := 0,
    alternative_motor_vehicle_credit := 0,
    alternative_fuel_vehicle_refueling_property_credit := 0,
    mine_rescue_team_training_credit := 0,
    agricultural_chemicals_security_credit := 0,
    differential_wage_payment_credit := 0,
    carbon_dioxide_sequestration_credit := 0,
    new_clean_vehicle_credit := 0,
    small_employer_health_insurance_credit := 0,
    paid_family_and_medical_leave_credit := 0,
    retirement_auto_enrollment_credit := 0,
    zero_emission_nuclear_power_production_credit := 0,
    sustainable_aviation_fuel_credit := 0,
    clean_hydrogen_production_credit := 0,
    qualified_commercial_clean_vehicle_credit := 0,
    advanced_manufacturing_production_credit := 0,
    clean_electricity_production_credit := 0,
    clean_fuel_production_credit := 0
  },
  carrybacks := 0
}

/-- 
  Theorem: The general business credit for the example inputs is 2000.
  Calculation: 1000 (carryforwards) + (500 + 200 + 300) (current year) + 0 (carrybacks) = 2000.
-/
theorem example_calculation_correct : calc_general_business_credit example_inputs = 2000 := by
  rfl