
/-
EDGE CASE TESTS: Vacuous Truth Patterns
Generated by loophole scanner
-/

import Mathlib
import TaxCode.Section831
import TaxCode.Section1297

set_option linter.unusedVariables false
noncomputable section

open Section831 in
/-!
## §831 Vacuous Truth Tests
The specified holder test passes when specifiedHolders is empty.
-/

-- Test 1: Concentrated ownership but NO specified holders
def concentratedButNoSpecified : InsuranceCompany := {
  id := 999
  taxYear := ⟨2024, by omega⟩
  netWrittenPremiums := 1000000
  directWrittenPremiums := 1000000
  investmentIncome := 50000
  underwritingIncome := 200000
  policyHolders := [
    -- ONE policyholder has 100% - FAILS 20% test!
    { id := 1, premiumsPaid := 1000000, isRelatedParty := false }
  ]
  specifiedHolders := []  -- EMPTY - vacuous pass!
  hasElected831b := true
  controlledGroupPremiums := 0
}

-- This SHOULD fail diversification but may pass due to vacuous truth
#eval! meetsNoPolicyholderOver20Test concentratedButNoSpecified  -- false (correctly fails)
#eval! meetsSpecifiedHolderTest concentratedButNoSpecified       -- true (vacuous!)
#eval! meetsDiversificationTest concentratedButNoSpecified       -- true (OR logic!)
#eval! qualifiesFor831b concentratedButNoSpecified               -- true (LOOPHOLE!)

-- Test 2: Empty policyholders list
def emptyPolicyholders : InsuranceCompany := {
  id := 998
  taxYear := ⟨2024, by omega⟩
  netWrittenPremiums := 0
  directWrittenPremiums := 0
  investmentIncome := 100000
  underwritingIncome := 0
  policyHolders := []  -- EMPTY
  specifiedHolders := []
  hasElected831b := true
  controlledGroupPremiums := 0
}

#eval! meetsNoPolicyholderOver20Test emptyPolicyholders  -- true (vacuous!)
#eval! meetsPremiumTest emptyPolicyholders               -- true (0 <= threshold)
#eval! qualifiesFor831b emptyPolicyholders               -- true (LOOPHOLE!)

/-!
## Division by Zero Tests
What happens when denominators are zero?
-/

-- Test 3: Zero total premiums
#eval! policyholderPremiumPercentage
  { id := 1, premiumsPaid := 1000000, isRelatedParty := false }
  emptyPolicyholders  -- Should be 0 (division guard)

/-!
## §1297 PFIC Threshold Tests
Testing the 75% and 50% boundaries.
-/

open Section1297 in
def pficAt74Percent : ForeignCorporation := {
  id := 100
  taxYear := ⟨2024, by omega⟩
  incomeItems := [
    { incomeType := .Dividends, amount := 74, fromRelatedParty := false, relatedPartyActiveIncome := 0 },
    { incomeType := .ActiveBusinessIncome, amount := 26, fromRelatedParty := false, relatedPartyActiveIncome := 0 }
  ]
  assets := []
  subsidiaryOwnership := []
  isCFC := false
  isQualifyingInsuranceCorp := false
  hasUSBankingLicense := false
}

def pficAt75Percent : ForeignCorporation := {
  id := 101
  taxYear := ⟨2024, by omega⟩
  incomeItems := [
    { incomeType := .Dividends, amount := 75, fromRelatedParty := false, relatedPartyActiveIncome := 0 },
    { incomeType := .ActiveBusinessIncome, amount := 25, fromRelatedParty := false, relatedPartyActiveIncome := 0 }
  ]
  assets := []
  subsidiaryOwnership := []
  isCFC := false
  isQualifyingInsuranceCorp := false
  hasUSBankingLicense := false
}

def pficAt76Percent : ForeignCorporation := {
  id := 102
  taxYear := ⟨2024, by omega⟩
  incomeItems := [
    { incomeType := .Dividends, amount := 76, fromRelatedParty := false, relatedPartyActiveIncome := 0 },
    { incomeType := .ActiveBusinessIncome, amount := 24, fromRelatedParty := false, relatedPartyActiveIncome := 0 }
  ]
  assets := []
  subsidiaryOwnership := []
  isCFC := false
  isQualifyingInsuranceCorp := false
  hasUSBankingLicense := false
}

#eval! passiveIncomeRatio pficAt74Percent  -- 74/100 = 0.74
#eval! passiveIncomeRatio pficAt75Percent  -- 75/100 = 0.75
#eval! passiveIncomeRatio pficAt76Percent  -- 76/100 = 0.76

#eval! isPFIC pficAt74Percent  -- false (just under!)
#eval! isPFIC pficAt75Percent  -- true (at threshold, >= means included)
#eval! isPFIC pficAt76Percent  -- true

-- Zero income edge case
def zeroIncomeCorp : ForeignCorporation := {
  id := 103
  taxYear := ⟨2024, by omega⟩
  incomeItems := []
  assets := []
  subsidiaryOwnership := []
  isCFC := false
  isQualifyingInsuranceCorp := false
  hasUSBankingLicense := false
}

#eval! grossIncome zeroIncomeCorp        -- 0
#eval! passiveIncomeRatio zeroIncomeCorp -- 0 (division guard)
#eval! isPFIC zeroIncomeCorp             -- false (0 < 75%)

-- CFC exemption test
def cfcButWouldBePfic : ForeignCorporation := {
  id := 104
  taxYear := ⟨2024, by omega⟩
  incomeItems := [
    { incomeType := .Interest, amount := 100, fromRelatedParty := false, relatedPartyActiveIncome := 0 }
  ]
  assets := []
  subsidiaryOwnership := []
  isCFC := true  -- IS a CFC
  isQualifyingInsuranceCorp := false
  hasUSBankingLicense := false
}

def us10PctShareholder : USPerson := {
  id := 1
  ownershipInCorp := 15 / 100
  isUS10PercentShareholder := true
}

#eval! isPFIC cfcButWouldBePfic  -- true (would be PFIC)
#eval! isPFICForShareholder cfcButWouldBePfic us10PctShareholder  -- false (CFC exempt!)

end
